// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cfb.proto

package ca.wise.fuel.proto;

public final class Cfb {
  private Cfb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_CfbC1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_CfbC1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_CfbC1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_CfbC1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_CfbD2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_CfbD2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_CfbD2_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_CfbD2_Parms_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcfb.proto\022\016WISE.FuelProto\032\nmath.proto\032" +
      "\017fuelNames.proto\"\234\003\n\005CfbC1\022\017\n\007version\030\001 " +
      "\001(\005\022+\n\007default\030\002 \001(\0162\030.WISE.FuelProto.Fu" +
      "elNameH\000\022,\n\005parms\030\003 \001(\0132\033.WISE.FuelProto" +
      ".CfbC1.ParmsH\000\032\237\002\n\005Parms\022\017\n\007version\030\001 \001(" +
      "\005\022#\n\rcsiMultiplier\030\002 \001(\0132\014.Math.Double\022$" +
      "\n\016csiCbhExponent\030\003 \001(\0132\014.Math.Double\022!\n\013" +
      "csiExpAdder\030\004 \001(\0132\014.Math.Double\022&\n\020csiEx" +
      "pMultiplier\030\005 \001(\0132\014.Math.Double\022\036\n\010csiPo" +
      "wer\030\006 \001(\0132\014.Math.Double\022\034\n\006rsoDiv\030\007 \001(\0132" +
      "\014.Math.Double\022\034\n\006cfbExp\030\010 \001(\0132\014.Math.Dou" +
      "ble\022\023\n\013cfbPossible\030\t \001(\010B\005\n\003msg\"\224\001\n\005CfbD" +
      "2\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030.WI" +
      "SE.FuelProto.FuelNameH\000\022,\n\005parms\030\003 \001(\0132\033" +
      ".WISE.FuelProto.CfbD2.ParmsH\000\032\030\n\005Parms\022\017" +
      "\n\007version\030\001 \001(\005B\005\n\003msgB\'\n\022ca.wise.fuel.p" +
      "rotoP\001\252\002\016WISE.FuelProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          ca.wise.fuel.proto.FuelNames.getDescriptor(),
        });
    internal_static_WISE_FuelProto_CfbC1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_FuelProto_CfbC1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_CfbC1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_CfbC1_Parms_descriptor =
      internal_static_WISE_FuelProto_CfbC1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_CfbC1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_CfbC1_Parms_descriptor,
        new java.lang.String[] { "Version", "CsiMultiplier", "CsiCbhExponent", "CsiExpAdder", "CsiExpMultiplier", "CsiPower", "RsoDiv", "CfbExp", "CfbPossible", });
    internal_static_WISE_FuelProto_CfbD2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WISE_FuelProto_CfbD2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_CfbD2_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_CfbD2_Parms_descriptor =
      internal_static_WISE_FuelProto_CfbD2_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_CfbD2_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_CfbD2_Parms_descriptor,
        new java.lang.String[] { "Version", });
    ca.hss.math.proto.Math.getDescriptor();
    ca.wise.fuel.proto.FuelNames.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
