// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccwfgmFuel.proto

package ca.wise.fuel.proto;

/**
 * Protobuf type {@code WISE.FuelProto.DbhAttribute}
 */
@java.lang.Deprecated public final class DbhAttribute extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.FuelProto.DbhAttribute)
    DbhAttributeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DbhAttribute.newBuilder() to construct.
  private DbhAttribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DbhAttribute() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DbhAttribute();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DbhAttribute(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            commonField_ = input.readInt64();
            break;
          }
          case 26: {
            ca.wise.fuel.proto.DbhNone.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((ca.wise.fuel.proto.DbhNone) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.DbhNone.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.DbhNone) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          case 34: {
            ca.wise.fuel.proto.DbhHuangCommon.Builder subBuilder = null;
            if (msgCase_ == 4) {
              subBuilder = ((ca.wise.fuel.proto.DbhHuangCommon) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.DbhHuangCommon.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.DbhHuangCommon) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 4;
            break;
          }
          case 42: {
            ca.wise.fuel.proto.Dbh1.Builder subBuilder = null;
            if (msgCase_ == 5) {
              subBuilder = ((ca.wise.fuel.proto.Dbh1) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.Dbh1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.Dbh1) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 5;
            break;
          }
          case 50: {
            ca.wise.fuel.proto.Dbh2.Builder subBuilder = null;
            if (msgCase_ == 6) {
              subBuilder = ((ca.wise.fuel.proto.Dbh2) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.Dbh2.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.Dbh2) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 6;
            break;
          }
          case 58: {
            ca.wise.fuel.proto.Dbh3.Builder subBuilder = null;
            if (msgCase_ == 7) {
              subBuilder = ((ca.wise.fuel.proto.Dbh3) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.Dbh3.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.Dbh3) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 7;
            break;
          }
          case 66: {
            ca.wise.fuel.proto.Dbh4.Builder subBuilder = null;
            if (msgCase_ == 8) {
              subBuilder = ((ca.wise.fuel.proto.Dbh4) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.Dbh4.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.Dbh4) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 8;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_DbhAttribute_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_DbhAttribute_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.fuel.proto.DbhAttribute.class, ca.wise.fuel.proto.DbhAttribute.Builder.class);
  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NONE(3),
    HUANGCOMMON(4),
    ONE(5),
    TWO(6),
    THREE(7),
    FOUR(8),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 3: return NONE;
        case 4: return HUANGCOMMON;
        case 5: return ONE;
        case 6: return TWO;
        case 7: return THREE;
        case 8: return FOUR;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int COMMONFIELD_FIELD_NUMBER = 2;
  private long commonField_;
  /**
   * <code>int64 commonField = 2 [deprecated = true];</code>
   * @return The commonField.
   */
  @java.lang.Override
  @java.lang.Deprecated public long getCommonField() {
    return commonField_;
  }

  public static final int NONE_FIELD_NUMBER = 3;
  /**
   * <code>.WISE.FuelProto.DbhNone none = 3;</code>
   * @return Whether the none field is set.
   */
  @java.lang.Override
  public boolean hasNone() {
    return msgCase_ == 3;
  }
  /**
   * <code>.WISE.FuelProto.DbhNone none = 3;</code>
   * @return The none.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.DbhNone getNone() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.DbhNone) msg_;
    }
    return ca.wise.fuel.proto.DbhNone.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.DbhNone none = 3;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.DbhNoneOrBuilder getNoneOrBuilder() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.DbhNone) msg_;
    }
    return ca.wise.fuel.proto.DbhNone.getDefaultInstance();
  }

  public static final int HUANGCOMMON_FIELD_NUMBER = 4;
  /**
   * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
   * @return Whether the huangCommon field is set.
   */
  @java.lang.Override
  public boolean hasHuangCommon() {
    return msgCase_ == 4;
  }
  /**
   * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
   * @return The huangCommon.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.DbhHuangCommon getHuangCommon() {
    if (msgCase_ == 4) {
       return (ca.wise.fuel.proto.DbhHuangCommon) msg_;
    }
    return ca.wise.fuel.proto.DbhHuangCommon.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.DbhHuangCommonOrBuilder getHuangCommonOrBuilder() {
    if (msgCase_ == 4) {
       return (ca.wise.fuel.proto.DbhHuangCommon) msg_;
    }
    return ca.wise.fuel.proto.DbhHuangCommon.getDefaultInstance();
  }

  public static final int ONE_FIELD_NUMBER = 5;
  /**
   * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
   * @return Whether the one field is set.
   */
  @java.lang.Override
  public boolean hasOne() {
    return msgCase_ == 5;
  }
  /**
   * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
   * @return The one.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh1 getOne() {
    if (msgCase_ == 5) {
       return (ca.wise.fuel.proto.Dbh1) msg_;
    }
    return ca.wise.fuel.proto.Dbh1.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh1OrBuilder getOneOrBuilder() {
    if (msgCase_ == 5) {
       return (ca.wise.fuel.proto.Dbh1) msg_;
    }
    return ca.wise.fuel.proto.Dbh1.getDefaultInstance();
  }

  public static final int TWO_FIELD_NUMBER = 6;
  /**
   * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
   * @return Whether the two field is set.
   */
  @java.lang.Override
  public boolean hasTwo() {
    return msgCase_ == 6;
  }
  /**
   * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
   * @return The two.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh2 getTwo() {
    if (msgCase_ == 6) {
       return (ca.wise.fuel.proto.Dbh2) msg_;
    }
    return ca.wise.fuel.proto.Dbh2.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh2OrBuilder getTwoOrBuilder() {
    if (msgCase_ == 6) {
       return (ca.wise.fuel.proto.Dbh2) msg_;
    }
    return ca.wise.fuel.proto.Dbh2.getDefaultInstance();
  }

  public static final int THREE_FIELD_NUMBER = 7;
  /**
   * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
   * @return Whether the three field is set.
   */
  @java.lang.Override
  public boolean hasThree() {
    return msgCase_ == 7;
  }
  /**
   * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
   * @return The three.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh3 getThree() {
    if (msgCase_ == 7) {
       return (ca.wise.fuel.proto.Dbh3) msg_;
    }
    return ca.wise.fuel.proto.Dbh3.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh3OrBuilder getThreeOrBuilder() {
    if (msgCase_ == 7) {
       return (ca.wise.fuel.proto.Dbh3) msg_;
    }
    return ca.wise.fuel.proto.Dbh3.getDefaultInstance();
  }

  public static final int FOUR_FIELD_NUMBER = 8;
  /**
   * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
   * @return Whether the four field is set.
   */
  @java.lang.Override
  public boolean hasFour() {
    return msgCase_ == 8;
  }
  /**
   * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
   * @return The four.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh4 getFour() {
    if (msgCase_ == 8) {
       return (ca.wise.fuel.proto.Dbh4) msg_;
    }
    return ca.wise.fuel.proto.Dbh4.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.Dbh4OrBuilder getFourOrBuilder() {
    if (msgCase_ == 8) {
       return (ca.wise.fuel.proto.Dbh4) msg_;
    }
    return ca.wise.fuel.proto.Dbh4.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (commonField_ != 0L) {
      output.writeInt64(2, commonField_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (ca.wise.fuel.proto.DbhNone) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (ca.wise.fuel.proto.DbhHuangCommon) msg_);
    }
    if (msgCase_ == 5) {
      output.writeMessage(5, (ca.wise.fuel.proto.Dbh1) msg_);
    }
    if (msgCase_ == 6) {
      output.writeMessage(6, (ca.wise.fuel.proto.Dbh2) msg_);
    }
    if (msgCase_ == 7) {
      output.writeMessage(7, (ca.wise.fuel.proto.Dbh3) msg_);
    }
    if (msgCase_ == 8) {
      output.writeMessage(8, (ca.wise.fuel.proto.Dbh4) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (commonField_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, commonField_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ca.wise.fuel.proto.DbhNone) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ca.wise.fuel.proto.DbhHuangCommon) msg_);
    }
    if (msgCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (ca.wise.fuel.proto.Dbh1) msg_);
    }
    if (msgCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (ca.wise.fuel.proto.Dbh2) msg_);
    }
    if (msgCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (ca.wise.fuel.proto.Dbh3) msg_);
    }
    if (msgCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (ca.wise.fuel.proto.Dbh4) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.fuel.proto.DbhAttribute)) {
      return super.equals(obj);
    }
    ca.wise.fuel.proto.DbhAttribute other = (ca.wise.fuel.proto.DbhAttribute) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (getCommonField()
        != other.getCommonField()) return false;
    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 3:
        if (!getNone()
            .equals(other.getNone())) return false;
        break;
      case 4:
        if (!getHuangCommon()
            .equals(other.getHuangCommon())) return false;
        break;
      case 5:
        if (!getOne()
            .equals(other.getOne())) return false;
        break;
      case 6:
        if (!getTwo()
            .equals(other.getTwo())) return false;
        break;
      case 7:
        if (!getThree()
            .equals(other.getThree())) return false;
        break;
      case 8:
        if (!getFour()
            .equals(other.getFour())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + COMMONFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommonField());
    switch (msgCase_) {
      case 3:
        hash = (37 * hash) + NONE_FIELD_NUMBER;
        hash = (53 * hash) + getNone().hashCode();
        break;
      case 4:
        hash = (37 * hash) + HUANGCOMMON_FIELD_NUMBER;
        hash = (53 * hash) + getHuangCommon().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ONE_FIELD_NUMBER;
        hash = (53 * hash) + getOne().hashCode();
        break;
      case 6:
        hash = (37 * hash) + TWO_FIELD_NUMBER;
        hash = (53 * hash) + getTwo().hashCode();
        break;
      case 7:
        hash = (37 * hash) + THREE_FIELD_NUMBER;
        hash = (53 * hash) + getThree().hashCode();
        break;
      case 8:
        hash = (37 * hash) + FOUR_FIELD_NUMBER;
        hash = (53 * hash) + getFour().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.DbhAttribute parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.fuel.proto.DbhAttribute prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.FuelProto.DbhAttribute}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.FuelProto.DbhAttribute)
      ca.wise.fuel.proto.DbhAttributeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_DbhAttribute_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_DbhAttribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.fuel.proto.DbhAttribute.class, ca.wise.fuel.proto.DbhAttribute.Builder.class);
    }

    // Construct using ca.wise.fuel.proto.DbhAttribute.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      commonField_ = 0L;

      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_DbhAttribute_descriptor;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.DbhAttribute getDefaultInstanceForType() {
      return ca.wise.fuel.proto.DbhAttribute.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.fuel.proto.DbhAttribute build() {
      ca.wise.fuel.proto.DbhAttribute result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.DbhAttribute buildPartial() {
      ca.wise.fuel.proto.DbhAttribute result = new ca.wise.fuel.proto.DbhAttribute(this);
      result.version_ = version_;
      result.commonField_ = commonField_;
      if (msgCase_ == 3) {
        if (noneBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = noneBuilder_.build();
        }
      }
      if (msgCase_ == 4) {
        if (huangCommonBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = huangCommonBuilder_.build();
        }
      }
      if (msgCase_ == 5) {
        if (oneBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = oneBuilder_.build();
        }
      }
      if (msgCase_ == 6) {
        if (twoBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = twoBuilder_.build();
        }
      }
      if (msgCase_ == 7) {
        if (threeBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = threeBuilder_.build();
        }
      }
      if (msgCase_ == 8) {
        if (fourBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = fourBuilder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.fuel.proto.DbhAttribute) {
        return mergeFrom((ca.wise.fuel.proto.DbhAttribute)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.fuel.proto.DbhAttribute other) {
      if (other == ca.wise.fuel.proto.DbhAttribute.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getCommonField() != 0L) {
        setCommonField(other.getCommonField());
      }
      switch (other.getMsgCase()) {
        case NONE: {
          mergeNone(other.getNone());
          break;
        }
        case HUANGCOMMON: {
          mergeHuangCommon(other.getHuangCommon());
          break;
        }
        case ONE: {
          mergeOne(other.getOne());
          break;
        }
        case TWO: {
          mergeTwo(other.getTwo());
          break;
        }
        case THREE: {
          mergeThree(other.getThree());
          break;
        }
        case FOUR: {
          mergeFour(other.getFour());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.fuel.proto.DbhAttribute parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.fuel.proto.DbhAttribute) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private long commonField_ ;
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @return The commonField.
     */
    @java.lang.Override
    @java.lang.Deprecated public long getCommonField() {
      return commonField_;
    }
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @param value The commonField to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setCommonField(long value) {
      
      commonField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearCommonField() {
      
      commonField_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.DbhNone, ca.wise.fuel.proto.DbhNone.Builder, ca.wise.fuel.proto.DbhNoneOrBuilder> noneBuilder_;
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     * @return Whether the none field is set.
     */
    @java.lang.Override
    public boolean hasNone() {
      return msgCase_ == 3;
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     * @return The none.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.DbhNone getNone() {
      if (noneBuilder_ == null) {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.DbhNone) msg_;
        }
        return ca.wise.fuel.proto.DbhNone.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return noneBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.DbhNone.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     */
    public Builder setNone(ca.wise.fuel.proto.DbhNone value) {
      if (noneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        noneBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     */
    public Builder setNone(
        ca.wise.fuel.proto.DbhNone.Builder builderForValue) {
      if (noneBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        noneBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     */
    public Builder mergeNone(ca.wise.fuel.proto.DbhNone value) {
      if (noneBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != ca.wise.fuel.proto.DbhNone.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.DbhNone.newBuilder((ca.wise.fuel.proto.DbhNone) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          noneBuilder_.mergeFrom(value);
        }
        noneBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     */
    public Builder clearNone() {
      if (noneBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        noneBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     */
    public ca.wise.fuel.proto.DbhNone.Builder getNoneBuilder() {
      return getNoneFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.DbhNoneOrBuilder getNoneOrBuilder() {
      if ((msgCase_ == 3) && (noneBuilder_ != null)) {
        return noneBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.DbhNone) msg_;
        }
        return ca.wise.fuel.proto.DbhNone.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.DbhNone none = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.DbhNone, ca.wise.fuel.proto.DbhNone.Builder, ca.wise.fuel.proto.DbhNoneOrBuilder> 
        getNoneFieldBuilder() {
      if (noneBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = ca.wise.fuel.proto.DbhNone.getDefaultInstance();
        }
        noneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.DbhNone, ca.wise.fuel.proto.DbhNone.Builder, ca.wise.fuel.proto.DbhNoneOrBuilder>(
                (ca.wise.fuel.proto.DbhNone) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return noneBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.DbhHuangCommon, ca.wise.fuel.proto.DbhHuangCommon.Builder, ca.wise.fuel.proto.DbhHuangCommonOrBuilder> huangCommonBuilder_;
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     * @return Whether the huangCommon field is set.
     */
    @java.lang.Override
    public boolean hasHuangCommon() {
      return msgCase_ == 4;
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     * @return The huangCommon.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.DbhHuangCommon getHuangCommon() {
      if (huangCommonBuilder_ == null) {
        if (msgCase_ == 4) {
          return (ca.wise.fuel.proto.DbhHuangCommon) msg_;
        }
        return ca.wise.fuel.proto.DbhHuangCommon.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return huangCommonBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.DbhHuangCommon.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     */
    public Builder setHuangCommon(ca.wise.fuel.proto.DbhHuangCommon value) {
      if (huangCommonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        huangCommonBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     */
    public Builder setHuangCommon(
        ca.wise.fuel.proto.DbhHuangCommon.Builder builderForValue) {
      if (huangCommonBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        huangCommonBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     */
    public Builder mergeHuangCommon(ca.wise.fuel.proto.DbhHuangCommon value) {
      if (huangCommonBuilder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != ca.wise.fuel.proto.DbhHuangCommon.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.DbhHuangCommon.newBuilder((ca.wise.fuel.proto.DbhHuangCommon) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          huangCommonBuilder_.mergeFrom(value);
        }
        huangCommonBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     */
    public Builder clearHuangCommon() {
      if (huangCommonBuilder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        huangCommonBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     */
    public ca.wise.fuel.proto.DbhHuangCommon.Builder getHuangCommonBuilder() {
      return getHuangCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.DbhHuangCommonOrBuilder getHuangCommonOrBuilder() {
      if ((msgCase_ == 4) && (huangCommonBuilder_ != null)) {
        return huangCommonBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (ca.wise.fuel.proto.DbhHuangCommon) msg_;
        }
        return ca.wise.fuel.proto.DbhHuangCommon.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.DbhHuangCommon huangCommon = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.DbhHuangCommon, ca.wise.fuel.proto.DbhHuangCommon.Builder, ca.wise.fuel.proto.DbhHuangCommonOrBuilder> 
        getHuangCommonFieldBuilder() {
      if (huangCommonBuilder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = ca.wise.fuel.proto.DbhHuangCommon.getDefaultInstance();
        }
        huangCommonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.DbhHuangCommon, ca.wise.fuel.proto.DbhHuangCommon.Builder, ca.wise.fuel.proto.DbhHuangCommonOrBuilder>(
                (ca.wise.fuel.proto.DbhHuangCommon) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();;
      return huangCommonBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh1, ca.wise.fuel.proto.Dbh1.Builder, ca.wise.fuel.proto.Dbh1OrBuilder> oneBuilder_;
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     * @return Whether the one field is set.
     */
    @java.lang.Override
    public boolean hasOne() {
      return msgCase_ == 5;
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     * @return The one.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh1 getOne() {
      if (oneBuilder_ == null) {
        if (msgCase_ == 5) {
          return (ca.wise.fuel.proto.Dbh1) msg_;
        }
        return ca.wise.fuel.proto.Dbh1.getDefaultInstance();
      } else {
        if (msgCase_ == 5) {
          return oneBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.Dbh1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     */
    public Builder setOne(ca.wise.fuel.proto.Dbh1 value) {
      if (oneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        oneBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     */
    public Builder setOne(
        ca.wise.fuel.proto.Dbh1.Builder builderForValue) {
      if (oneBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        oneBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     */
    public Builder mergeOne(ca.wise.fuel.proto.Dbh1 value) {
      if (oneBuilder_ == null) {
        if (msgCase_ == 5 &&
            msg_ != ca.wise.fuel.proto.Dbh1.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.Dbh1.newBuilder((ca.wise.fuel.proto.Dbh1) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 5) {
          oneBuilder_.mergeFrom(value);
        }
        oneBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     */
    public Builder clearOne() {
      if (oneBuilder_ == null) {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
        }
        oneBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     */
    public ca.wise.fuel.proto.Dbh1.Builder getOneBuilder() {
      return getOneFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh1OrBuilder getOneOrBuilder() {
      if ((msgCase_ == 5) && (oneBuilder_ != null)) {
        return oneBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 5) {
          return (ca.wise.fuel.proto.Dbh1) msg_;
        }
        return ca.wise.fuel.proto.Dbh1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh1 one = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh1, ca.wise.fuel.proto.Dbh1.Builder, ca.wise.fuel.proto.Dbh1OrBuilder> 
        getOneFieldBuilder() {
      if (oneBuilder_ == null) {
        if (!(msgCase_ == 5)) {
          msg_ = ca.wise.fuel.proto.Dbh1.getDefaultInstance();
        }
        oneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.Dbh1, ca.wise.fuel.proto.Dbh1.Builder, ca.wise.fuel.proto.Dbh1OrBuilder>(
                (ca.wise.fuel.proto.Dbh1) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 5;
      onChanged();;
      return oneBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh2, ca.wise.fuel.proto.Dbh2.Builder, ca.wise.fuel.proto.Dbh2OrBuilder> twoBuilder_;
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     * @return Whether the two field is set.
     */
    @java.lang.Override
    public boolean hasTwo() {
      return msgCase_ == 6;
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     * @return The two.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh2 getTwo() {
      if (twoBuilder_ == null) {
        if (msgCase_ == 6) {
          return (ca.wise.fuel.proto.Dbh2) msg_;
        }
        return ca.wise.fuel.proto.Dbh2.getDefaultInstance();
      } else {
        if (msgCase_ == 6) {
          return twoBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.Dbh2.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     */
    public Builder setTwo(ca.wise.fuel.proto.Dbh2 value) {
      if (twoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        twoBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     */
    public Builder setTwo(
        ca.wise.fuel.proto.Dbh2.Builder builderForValue) {
      if (twoBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        twoBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     */
    public Builder mergeTwo(ca.wise.fuel.proto.Dbh2 value) {
      if (twoBuilder_ == null) {
        if (msgCase_ == 6 &&
            msg_ != ca.wise.fuel.proto.Dbh2.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.Dbh2.newBuilder((ca.wise.fuel.proto.Dbh2) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 6) {
          twoBuilder_.mergeFrom(value);
        }
        twoBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     */
    public Builder clearTwo() {
      if (twoBuilder_ == null) {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
        }
        twoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     */
    public ca.wise.fuel.proto.Dbh2.Builder getTwoBuilder() {
      return getTwoFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh2OrBuilder getTwoOrBuilder() {
      if ((msgCase_ == 6) && (twoBuilder_ != null)) {
        return twoBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 6) {
          return (ca.wise.fuel.proto.Dbh2) msg_;
        }
        return ca.wise.fuel.proto.Dbh2.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh2 two = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh2, ca.wise.fuel.proto.Dbh2.Builder, ca.wise.fuel.proto.Dbh2OrBuilder> 
        getTwoFieldBuilder() {
      if (twoBuilder_ == null) {
        if (!(msgCase_ == 6)) {
          msg_ = ca.wise.fuel.proto.Dbh2.getDefaultInstance();
        }
        twoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.Dbh2, ca.wise.fuel.proto.Dbh2.Builder, ca.wise.fuel.proto.Dbh2OrBuilder>(
                (ca.wise.fuel.proto.Dbh2) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 6;
      onChanged();;
      return twoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh3, ca.wise.fuel.proto.Dbh3.Builder, ca.wise.fuel.proto.Dbh3OrBuilder> threeBuilder_;
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     * @return Whether the three field is set.
     */
    @java.lang.Override
    public boolean hasThree() {
      return msgCase_ == 7;
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     * @return The three.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh3 getThree() {
      if (threeBuilder_ == null) {
        if (msgCase_ == 7) {
          return (ca.wise.fuel.proto.Dbh3) msg_;
        }
        return ca.wise.fuel.proto.Dbh3.getDefaultInstance();
      } else {
        if (msgCase_ == 7) {
          return threeBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.Dbh3.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     */
    public Builder setThree(ca.wise.fuel.proto.Dbh3 value) {
      if (threeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        threeBuilder_.setMessage(value);
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     */
    public Builder setThree(
        ca.wise.fuel.proto.Dbh3.Builder builderForValue) {
      if (threeBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        threeBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     */
    public Builder mergeThree(ca.wise.fuel.proto.Dbh3 value) {
      if (threeBuilder_ == null) {
        if (msgCase_ == 7 &&
            msg_ != ca.wise.fuel.proto.Dbh3.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.Dbh3.newBuilder((ca.wise.fuel.proto.Dbh3) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 7) {
          threeBuilder_.mergeFrom(value);
        }
        threeBuilder_.setMessage(value);
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     */
    public Builder clearThree() {
      if (threeBuilder_ == null) {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
        }
        threeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     */
    public ca.wise.fuel.proto.Dbh3.Builder getThreeBuilder() {
      return getThreeFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh3OrBuilder getThreeOrBuilder() {
      if ((msgCase_ == 7) && (threeBuilder_ != null)) {
        return threeBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 7) {
          return (ca.wise.fuel.proto.Dbh3) msg_;
        }
        return ca.wise.fuel.proto.Dbh3.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh3 three = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh3, ca.wise.fuel.proto.Dbh3.Builder, ca.wise.fuel.proto.Dbh3OrBuilder> 
        getThreeFieldBuilder() {
      if (threeBuilder_ == null) {
        if (!(msgCase_ == 7)) {
          msg_ = ca.wise.fuel.proto.Dbh3.getDefaultInstance();
        }
        threeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.Dbh3, ca.wise.fuel.proto.Dbh3.Builder, ca.wise.fuel.proto.Dbh3OrBuilder>(
                (ca.wise.fuel.proto.Dbh3) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 7;
      onChanged();;
      return threeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh4, ca.wise.fuel.proto.Dbh4.Builder, ca.wise.fuel.proto.Dbh4OrBuilder> fourBuilder_;
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     * @return Whether the four field is set.
     */
    @java.lang.Override
    public boolean hasFour() {
      return msgCase_ == 8;
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     * @return The four.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh4 getFour() {
      if (fourBuilder_ == null) {
        if (msgCase_ == 8) {
          return (ca.wise.fuel.proto.Dbh4) msg_;
        }
        return ca.wise.fuel.proto.Dbh4.getDefaultInstance();
      } else {
        if (msgCase_ == 8) {
          return fourBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.Dbh4.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     */
    public Builder setFour(ca.wise.fuel.proto.Dbh4 value) {
      if (fourBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        fourBuilder_.setMessage(value);
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     */
    public Builder setFour(
        ca.wise.fuel.proto.Dbh4.Builder builderForValue) {
      if (fourBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        fourBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     */
    public Builder mergeFour(ca.wise.fuel.proto.Dbh4 value) {
      if (fourBuilder_ == null) {
        if (msgCase_ == 8 &&
            msg_ != ca.wise.fuel.proto.Dbh4.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.Dbh4.newBuilder((ca.wise.fuel.proto.Dbh4) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 8) {
          fourBuilder_.mergeFrom(value);
        }
        fourBuilder_.setMessage(value);
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     */
    public Builder clearFour() {
      if (fourBuilder_ == null) {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
        }
        fourBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     */
    public ca.wise.fuel.proto.Dbh4.Builder getFourBuilder() {
      return getFourFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.Dbh4OrBuilder getFourOrBuilder() {
      if ((msgCase_ == 8) && (fourBuilder_ != null)) {
        return fourBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 8) {
          return (ca.wise.fuel.proto.Dbh4) msg_;
        }
        return ca.wise.fuel.proto.Dbh4.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.Dbh4 four = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.Dbh4, ca.wise.fuel.proto.Dbh4.Builder, ca.wise.fuel.proto.Dbh4OrBuilder> 
        getFourFieldBuilder() {
      if (fourBuilder_ == null) {
        if (!(msgCase_ == 8)) {
          msg_ = ca.wise.fuel.proto.Dbh4.getDefaultInstance();
        }
        fourBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.Dbh4, ca.wise.fuel.proto.Dbh4.Builder, ca.wise.fuel.proto.Dbh4OrBuilder>(
                (ca.wise.fuel.proto.Dbh4) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 8;
      onChanged();;
      return fourBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.FuelProto.DbhAttribute)
  }

  // @@protoc_insertion_point(class_scope:WISE.FuelProto.DbhAttribute)
  private static final ca.wise.fuel.proto.DbhAttribute DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.fuel.proto.DbhAttribute();
  }

  public static ca.wise.fuel.proto.DbhAttribute getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DbhAttribute>
      PARSER = new com.google.protobuf.AbstractParser<DbhAttribute>() {
    @java.lang.Override
    public DbhAttribute parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DbhAttribute(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DbhAttribute> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DbhAttribute> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.fuel.proto.DbhAttribute getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

