// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccwfgmFuel.proto

package ca.wise.fuel.proto;

public interface FbpFuelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.FuelProto.FbpFuel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>string loadWarning = 2;</code>
   * @return The loadWarning.
   */
  java.lang.String getLoadWarning();
  /**
   * <code>string loadWarning = 2;</code>
   * @return The bytes for loadWarning.
   */
  com.google.protobuf.ByteString
      getLoadWarningBytes();

  /**
   * <code>bool fuelTypeModified = 3;</code>
   * @return The fuelTypeModified.
   */
  boolean getFuelTypeModified();

  /**
   * <code>.WISE.FuelProto.FuelName defaultFuelType = 4;</code>
   * @return The enum numeric value on the wire for defaultFuelType.
   */
  int getDefaultFuelTypeValue();
  /**
   * <code>.WISE.FuelProto.FuelName defaultFuelType = 4;</code>
   * @return The defaultFuelType.
   */
  ca.wise.fuel.proto.FuelName getDefaultFuelType();

  /**
   * <code>.WISE.FuelProto.SpreadParmsAttribute spread = 5;</code>
   * @return Whether the spread field is set.
   */
  boolean hasSpread();
  /**
   * <code>.WISE.FuelProto.SpreadParmsAttribute spread = 5;</code>
   * @return The spread.
   */
  ca.wise.fuel.proto.SpreadParmsAttribute getSpread();
  /**
   * <code>.WISE.FuelProto.SpreadParmsAttribute spread = 5;</code>
   */
  ca.wise.fuel.proto.SpreadParmsAttributeOrBuilder getSpreadOrBuilder();

  /**
   * <code>.WISE.FuelProto.FmcAttribute fmcCalculation = 6;</code>
   * @return Whether the fmcCalculation field is set.
   */
  boolean hasFmcCalculation();
  /**
   * <code>.WISE.FuelProto.FmcAttribute fmcCalculation = 6;</code>
   * @return The fmcCalculation.
   */
  ca.wise.fuel.proto.FmcAttribute getFmcCalculation();
  /**
   * <code>.WISE.FuelProto.FmcAttribute fmcCalculation = 6;</code>
   */
  ca.wise.fuel.proto.FmcAttributeOrBuilder getFmcCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.SfcAttribute sfcCalculation = 7;</code>
   * @return Whether the sfcCalculation field is set.
   */
  boolean hasSfcCalculation();
  /**
   * <code>.WISE.FuelProto.SfcAttribute sfcCalculation = 7;</code>
   * @return The sfcCalculation.
   */
  ca.wise.fuel.proto.SfcAttribute getSfcCalculation();
  /**
   * <code>.WISE.FuelProto.SfcAttribute sfcCalculation = 7;</code>
   */
  ca.wise.fuel.proto.SfcAttributeOrBuilder getSfcCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.TfcAttribute tfcCalculation = 8;</code>
   * @return Whether the tfcCalculation field is set.
   */
  boolean hasTfcCalculation();
  /**
   * <code>.WISE.FuelProto.TfcAttribute tfcCalculation = 8;</code>
   * @return The tfcCalculation.
   */
  ca.wise.fuel.proto.TfcAttribute getTfcCalculation();
  /**
   * <code>.WISE.FuelProto.TfcAttribute tfcCalculation = 8;</code>
   */
  ca.wise.fuel.proto.TfcAttributeOrBuilder getTfcCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.RsiAttribute rsiCalculation = 9;</code>
   * @return Whether the rsiCalculation field is set.
   */
  boolean hasRsiCalculation();
  /**
   * <code>.WISE.FuelProto.RsiAttribute rsiCalculation = 9;</code>
   * @return The rsiCalculation.
   */
  ca.wise.fuel.proto.RsiAttribute getRsiCalculation();
  /**
   * <code>.WISE.FuelProto.RsiAttribute rsiCalculation = 9;</code>
   */
  ca.wise.fuel.proto.RsiAttributeOrBuilder getRsiCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.IsfAttribute isfCalculation = 10;</code>
   * @return Whether the isfCalculation field is set.
   */
  boolean hasIsfCalculation();
  /**
   * <code>.WISE.FuelProto.IsfAttribute isfCalculation = 10;</code>
   * @return The isfCalculation.
   */
  ca.wise.fuel.proto.IsfAttribute getIsfCalculation();
  /**
   * <code>.WISE.FuelProto.IsfAttribute isfCalculation = 10;</code>
   */
  ca.wise.fuel.proto.IsfAttributeOrBuilder getIsfCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.AccAlphaAttribute accAlphaCalculation = 11;</code>
   * @return Whether the accAlphaCalculation field is set.
   */
  boolean hasAccAlphaCalculation();
  /**
   * <code>.WISE.FuelProto.AccAlphaAttribute accAlphaCalculation = 11;</code>
   * @return The accAlphaCalculation.
   */
  ca.wise.fuel.proto.AccAlphaAttribute getAccAlphaCalculation();
  /**
   * <code>.WISE.FuelProto.AccAlphaAttribute accAlphaCalculation = 11;</code>
   */
  ca.wise.fuel.proto.AccAlphaAttributeOrBuilder getAccAlphaCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.LbAttribute lbCalculation = 12;</code>
   * @return Whether the lbCalculation field is set.
   */
  boolean hasLbCalculation();
  /**
   * <code>.WISE.FuelProto.LbAttribute lbCalculation = 12;</code>
   * @return The lbCalculation.
   */
  ca.wise.fuel.proto.LbAttribute getLbCalculation();
  /**
   * <code>.WISE.FuelProto.LbAttribute lbCalculation = 12;</code>
   */
  ca.wise.fuel.proto.LbAttributeOrBuilder getLbCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.CfbAttribute cfbCalculation = 13;</code>
   * @return Whether the cfbCalculation field is set.
   */
  boolean hasCfbCalculation();
  /**
   * <code>.WISE.FuelProto.CfbAttribute cfbCalculation = 13;</code>
   * @return The cfbCalculation.
   */
  ca.wise.fuel.proto.CfbAttribute getCfbCalculation();
  /**
   * <code>.WISE.FuelProto.CfbAttribute cfbCalculation = 13;</code>
   */
  ca.wise.fuel.proto.CfbAttributeOrBuilder getCfbCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.DbhAttribute dbhCalculation = 14;</code>
   * @return Whether the dbhCalculation field is set.
   */
  boolean hasDbhCalculation();
  /**
   * <code>.WISE.FuelProto.DbhAttribute dbhCalculation = 14;</code>
   * @return The dbhCalculation.
   */
  ca.wise.fuel.proto.DbhAttribute getDbhCalculation();
  /**
   * <code>.WISE.FuelProto.DbhAttribute dbhCalculation = 14;</code>
   */
  ca.wise.fuel.proto.DbhAttributeOrBuilder getDbhCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.FlameLengthAttribute flCalculation = 15;</code>
   * @return Whether the flCalculation field is set.
   */
  boolean hasFlCalculation();
  /**
   * <code>.WISE.FuelProto.FlameLengthAttribute flCalculation = 15;</code>
   * @return The flCalculation.
   */
  ca.wise.fuel.proto.FlameLengthAttribute getFlCalculation();
  /**
   * <code>.WISE.FuelProto.FlameLengthAttribute flCalculation = 15;</code>
   */
  ca.wise.fuel.proto.FlameLengthAttributeOrBuilder getFlCalculationOrBuilder();

  /**
   * <code>.WISE.FuelProto.SfcAttribute sfcCalculationGreenup = 16;</code>
   * @return Whether the sfcCalculationGreenup field is set.
   */
  boolean hasSfcCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.SfcAttribute sfcCalculationGreenup = 16;</code>
   * @return The sfcCalculationGreenup.
   */
  ca.wise.fuel.proto.SfcAttribute getSfcCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.SfcAttribute sfcCalculationGreenup = 16;</code>
   */
  ca.wise.fuel.proto.SfcAttributeOrBuilder getSfcCalculationGreenupOrBuilder();

  /**
   * <code>.WISE.FuelProto.TfcAttribute tfcCalculationGreenup = 17;</code>
   * @return Whether the tfcCalculationGreenup field is set.
   */
  boolean hasTfcCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.TfcAttribute tfcCalculationGreenup = 17;</code>
   * @return The tfcCalculationGreenup.
   */
  ca.wise.fuel.proto.TfcAttribute getTfcCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.TfcAttribute tfcCalculationGreenup = 17;</code>
   */
  ca.wise.fuel.proto.TfcAttributeOrBuilder getTfcCalculationGreenupOrBuilder();

  /**
   * <code>.WISE.FuelProto.RsiAttribute rsiCalculationGreenup = 18;</code>
   * @return Whether the rsiCalculationGreenup field is set.
   */
  boolean hasRsiCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.RsiAttribute rsiCalculationGreenup = 18;</code>
   * @return The rsiCalculationGreenup.
   */
  ca.wise.fuel.proto.RsiAttribute getRsiCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.RsiAttribute rsiCalculationGreenup = 18;</code>
   */
  ca.wise.fuel.proto.RsiAttributeOrBuilder getRsiCalculationGreenupOrBuilder();

  /**
   * <code>.WISE.FuelProto.IsfAttribute isfCalculationGreenup = 19;</code>
   * @return Whether the isfCalculationGreenup field is set.
   */
  boolean hasIsfCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.IsfAttribute isfCalculationGreenup = 19;</code>
   * @return The isfCalculationGreenup.
   */
  ca.wise.fuel.proto.IsfAttribute getIsfCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.IsfAttribute isfCalculationGreenup = 19;</code>
   */
  ca.wise.fuel.proto.IsfAttributeOrBuilder getIsfCalculationGreenupOrBuilder();

  /**
   * <code>.WISE.FuelProto.CfbAttribute cfbCalculationGreenup = 20;</code>
   * @return Whether the cfbCalculationGreenup field is set.
   */
  boolean hasCfbCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.CfbAttribute cfbCalculationGreenup = 20;</code>
   * @return The cfbCalculationGreenup.
   */
  ca.wise.fuel.proto.CfbAttribute getCfbCalculationGreenup();
  /**
   * <code>.WISE.FuelProto.CfbAttribute cfbCalculationGreenup = 20;</code>
   */
  ca.wise.fuel.proto.CfbAttributeOrBuilder getCfbCalculationGreenupOrBuilder();
}
