// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flame.proto

package ca.wise.fuel.proto;

public final class Flame {
  private Flame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthAlexander82_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthAlexander82_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthAlexander82_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthAlexander82_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthTree_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthTree_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthTree_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthTree_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthOther_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthOther_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_FlameLengthOther_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_FlameLengthOther_Parms_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013flame.proto\022\016WISE.FuelProto\032\nmath.prot" +
      "o\032\017fuelNames.proto\"\352\001\n\026FlameLengthAlexan" +
      "der82\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\0162" +
      "\030.WISE.FuelProto.FuelNameH\000\022=\n\005parms\030\003 \001" +
      "(\0132,.WISE.FuelProto.FlameLengthAlexander" +
      "82.ParmsH\000\032L\n\005Parms\022\017\n\007version\030\001 \001(\005\022\030\n\002" +
      "p1\030\002 \001(\0132\014.Math.Double\022\030\n\002p2\030\003 \001(\0132\014.Mat" +
      "h.DoubleB\005\n\003msg\"\250\002\n\032FlameLengthAlexander" +
      "82Tree\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\016" +
      "2\030.WISE.FuelProto.FuelNameH\000\022A\n\005parms\030\003 " +
      "\001(\01320.WISE.FuelProto.FlameLengthAlexande" +
      "r82Tree.ParmsH\000\032\201\001\n\005Parms\022\017\n\007version\030\001 \001" +
      "(\005\022\030\n\002p1\030\002 \001(\0132\014.Math.Double\022\030\n\002p2\030\003 \001(\013" +
      "2\014.Math.Double\022\031\n\003cfb\030\004 \001(\0132\014.Math.Doubl" +
      "e\022\030\n\002th\030\005 \001(\0132\014.Math.DoubleB\005\n\003msg\"\367\001\n\017F" +
      "lameLengthTree\022\017\n\007version\030\001 \001(\005\022+\n\007defau" +
      "lt\030\002 \001(\0162\030.WISE.FuelProto.FuelNameH\000\0226\n\005" +
      "parms\030\003 \001(\0132%.WISE.FuelProto.FlameLength" +
      "Tree.ParmsH\000\032g\n\005Parms\022\017\n\007version\030\001 \001(\005\022\030" +
      "\n\002p1\030\002 \001(\0132\014.Math.Double\022\030\n\002th\030\003 \001(\0132\014.M" +
      "ath.Double\022\031\n\003cfb\030\004 \001(\0132\014.Math.DoubleB\005\n" +
      "\003msg\"\304\001\n\020FlameLengthOther\022\017\n\007version\030\001 \001" +
      "(\005\022+\n\007default\030\002 \001(\0162\030.WISE.FuelProto.Fue" +
      "lNameH\000\0227\n\005parms\030\003 \001(\0132&.WISE.FuelProto." +
      "FlameLengthOther.ParmsH\000\0322\n\005Parms\022\017\n\007ver" +
      "sion\030\001 \001(\005\022\030\n\002p1\030\002 \001(\0132\014.Math.DoubleB\005\n\003" +
      "msgB\'\n\022ca.wise.fuel.protoP\001\252\002\016WISE.FuelP" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          ca.wise.fuel.proto.FuelNames.getDescriptor(),
        });
    internal_static_WISE_FuelProto_FlameLengthAlexander82_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_FuelProto_FlameLengthAlexander82_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthAlexander82_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_FlameLengthAlexander82_Parms_descriptor =
      internal_static_WISE_FuelProto_FlameLengthAlexander82_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_FlameLengthAlexander82_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthAlexander82_Parms_descriptor,
        new java.lang.String[] { "Version", "P1", "P2", });
    internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_Parms_descriptor =
      internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthAlexander82Tree_Parms_descriptor,
        new java.lang.String[] { "Version", "P1", "P2", "Cfb", "Th", });
    internal_static_WISE_FuelProto_FlameLengthTree_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WISE_FuelProto_FlameLengthTree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthTree_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_FlameLengthTree_Parms_descriptor =
      internal_static_WISE_FuelProto_FlameLengthTree_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_FlameLengthTree_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthTree_Parms_descriptor,
        new java.lang.String[] { "Version", "P1", "Th", "Cfb", });
    internal_static_WISE_FuelProto_FlameLengthOther_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WISE_FuelProto_FlameLengthOther_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthOther_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_FlameLengthOther_Parms_descriptor =
      internal_static_WISE_FuelProto_FlameLengthOther_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_FlameLengthOther_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_FlameLengthOther_Parms_descriptor,
        new java.lang.String[] { "Version", "P1", });
    ca.hss.math.proto.Math.getDescriptor();
    ca.wise.fuel.proto.FuelNames.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
