// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fuelNames.proto

package ca.wise.fuel.proto;

/**
 * Protobuf enum {@code WISE.FuelProto.FuelName}
 */
public enum FuelName
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>unset = 0;</code>
   */
  unset(0),
  /**
   * <code>C1 = 1;</code>
   */
  C1(1),
  /**
   * <code>C2 = 2;</code>
   */
  C2(2),
  /**
   * <code>C3 = 3;</code>
   */
  C3(3),
  /**
   * <code>C4 = 4;</code>
   */
  C4(4),
  /**
   * <code>C5 = 5;</code>
   */
  C5(5),
  /**
   * <code>C6 = 6;</code>
   */
  C6(6),
  /**
   * <code>C7 = 7;</code>
   */
  C7(7),
  /**
   * <code>D1 = 11;</code>
   */
  D1(11),
  /**
   * <code>D2 = 12;</code>
   */
  D2(12),
  /**
   * <code>D1D2 = 13;</code>
   */
  D1D2(13),
  /**
   * <code>M1 = 21;</code>
   */
  M1(21),
  /**
   * <code>M2 = 22;</code>
   */
  M2(22),
  /**
   * <code>M1M2 = 23;</code>
   */
  M1M2(23),
  /**
   * <code>M3 = 24;</code>
   */
  M3(24),
  /**
   * <code>M4 = 25;</code>
   */
  M4(25),
  /**
   * <code>M3M4 = 26;</code>
   */
  M3M4(26),
  /**
   * <code>O1A = 31;</code>
   */
  O1A(31),
  /**
   * <code>O1B = 32;</code>
   */
  O1B(32),
  /**
   * <code>O1AB = 33;</code>
   */
  O1AB(33),
  /**
   * <code>S1 = 41;</code>
   */
  S1(41),
  /**
   * <code>S2 = 42;</code>
   */
  S2(42),
  /**
   * <code>S3 = 43;</code>
   */
  S3(43),
  /**
   * <code>Non = 51;</code>
   */
  Non(51),
  /**
   * <code>Nz2 = 62;</code>
   */
  Nz2(62),
  /**
   * <code>Nz15 = 75;</code>
   */
  Nz15(75),
  /**
   * <code>Nz30 = 90;</code>
   */
  Nz30(90),
  /**
   * <code>Nz31 = 91;</code>
   */
  Nz31(91),
  /**
   * <code>Nz32 = 92;</code>
   */
  Nz32(92),
  /**
   * <code>Nz33 = 93;</code>
   */
  Nz33(93),
  /**
   * <code>Nz40 = 100;</code>
   */
  Nz40(100),
  /**
   * <code>Nz41 = 101;</code>
   */
  Nz41(101),
  /**
   * <code>Nz43 = 103;</code>
   */
  Nz43(103),
  /**
   * <code>Nz44 = 104;</code>
   */
  Nz44(104),
  /**
   * <code>Nz45 = 105;</code>
   */
  Nz45(105),
  /**
   * <code>Nz46 = 106;</code>
   */
  Nz46(106),
  /**
   * <code>Nz47 = 107;</code>
   */
  Nz47(107),
  /**
   * <code>Nz50 = 110;</code>
   */
  Nz50(110),
  /**
   * <code>Nz51 = 111;</code>
   */
  Nz51(111),
  /**
   * <code>Nz52 = 112;</code>
   */
  Nz52(112),
  /**
   * <code>Nz53 = 113;</code>
   */
  Nz53(113),
  /**
   * <code>Nz54 = 114;</code>
   */
  Nz54(114),
  /**
   * <code>Nz55 = 115;</code>
   */
  Nz55(115),
  /**
   * <code>Nz56 = 116;</code>
   */
  Nz56(116),
  /**
   * <code>Nz57 = 117;</code>
   */
  Nz57(117),
  /**
   * <code>Nz58 = 118;</code>
   */
  Nz58(118),
  /**
   * <code>Nz60 = 120;</code>
   */
  Nz60(120),
  /**
   * <code>Nz61 = 121;</code>
   */
  Nz61(121),
  /**
   * <code>Nz62 = 122;</code>
   */
  Nz62(122),
  /**
   * <code>Nz63 = 123;</code>
   */
  Nz63(123),
  /**
   * <code>Nz64 = 124;</code>
   */
  Nz64(124),
  /**
   * <code>Nz65 = 125;</code>
   */
  Nz65(125),
  /**
   * <code>Nz66 = 126;</code>
   */
  Nz66(126),
  /**
   * <code>Nz67 = 127;</code>
   */
  Nz67(127),
  /**
   * <code>Nz68 = 128;</code>
   */
  Nz68(128),
  /**
   * <code>Nz69 = 129;</code>
   */
  Nz69(129),
  /**
   * <code>Nz70 = 130;</code>
   */
  Nz70(130),
  /**
   * <code>Nz71 = 131;</code>
   */
  Nz71(131),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>unset = 0;</code>
   */
  public static final int unset_VALUE = 0;
  /**
   * <code>C1 = 1;</code>
   */
  public static final int C1_VALUE = 1;
  /**
   * <code>C2 = 2;</code>
   */
  public static final int C2_VALUE = 2;
  /**
   * <code>C3 = 3;</code>
   */
  public static final int C3_VALUE = 3;
  /**
   * <code>C4 = 4;</code>
   */
  public static final int C4_VALUE = 4;
  /**
   * <code>C5 = 5;</code>
   */
  public static final int C5_VALUE = 5;
  /**
   * <code>C6 = 6;</code>
   */
  public static final int C6_VALUE = 6;
  /**
   * <code>C7 = 7;</code>
   */
  public static final int C7_VALUE = 7;
  /**
   * <code>D1 = 11;</code>
   */
  public static final int D1_VALUE = 11;
  /**
   * <code>D2 = 12;</code>
   */
  public static final int D2_VALUE = 12;
  /**
   * <code>D1D2 = 13;</code>
   */
  public static final int D1D2_VALUE = 13;
  /**
   * <code>M1 = 21;</code>
   */
  public static final int M1_VALUE = 21;
  /**
   * <code>M2 = 22;</code>
   */
  public static final int M2_VALUE = 22;
  /**
   * <code>M1M2 = 23;</code>
   */
  public static final int M1M2_VALUE = 23;
  /**
   * <code>M3 = 24;</code>
   */
  public static final int M3_VALUE = 24;
  /**
   * <code>M4 = 25;</code>
   */
  public static final int M4_VALUE = 25;
  /**
   * <code>M3M4 = 26;</code>
   */
  public static final int M3M4_VALUE = 26;
  /**
   * <code>O1A = 31;</code>
   */
  public static final int O1A_VALUE = 31;
  /**
   * <code>O1B = 32;</code>
   */
  public static final int O1B_VALUE = 32;
  /**
   * <code>O1AB = 33;</code>
   */
  public static final int O1AB_VALUE = 33;
  /**
   * <code>S1 = 41;</code>
   */
  public static final int S1_VALUE = 41;
  /**
   * <code>S2 = 42;</code>
   */
  public static final int S2_VALUE = 42;
  /**
   * <code>S3 = 43;</code>
   */
  public static final int S3_VALUE = 43;
  /**
   * <code>Non = 51;</code>
   */
  public static final int Non_VALUE = 51;
  /**
   * <code>Nz2 = 62;</code>
   */
  public static final int Nz2_VALUE = 62;
  /**
   * <code>Nz15 = 75;</code>
   */
  public static final int Nz15_VALUE = 75;
  /**
   * <code>Nz30 = 90;</code>
   */
  public static final int Nz30_VALUE = 90;
  /**
   * <code>Nz31 = 91;</code>
   */
  public static final int Nz31_VALUE = 91;
  /**
   * <code>Nz32 = 92;</code>
   */
  public static final int Nz32_VALUE = 92;
  /**
   * <code>Nz33 = 93;</code>
   */
  public static final int Nz33_VALUE = 93;
  /**
   * <code>Nz40 = 100;</code>
   */
  public static final int Nz40_VALUE = 100;
  /**
   * <code>Nz41 = 101;</code>
   */
  public static final int Nz41_VALUE = 101;
  /**
   * <code>Nz43 = 103;</code>
   */
  public static final int Nz43_VALUE = 103;
  /**
   * <code>Nz44 = 104;</code>
   */
  public static final int Nz44_VALUE = 104;
  /**
   * <code>Nz45 = 105;</code>
   */
  public static final int Nz45_VALUE = 105;
  /**
   * <code>Nz46 = 106;</code>
   */
  public static final int Nz46_VALUE = 106;
  /**
   * <code>Nz47 = 107;</code>
   */
  public static final int Nz47_VALUE = 107;
  /**
   * <code>Nz50 = 110;</code>
   */
  public static final int Nz50_VALUE = 110;
  /**
   * <code>Nz51 = 111;</code>
   */
  public static final int Nz51_VALUE = 111;
  /**
   * <code>Nz52 = 112;</code>
   */
  public static final int Nz52_VALUE = 112;
  /**
   * <code>Nz53 = 113;</code>
   */
  public static final int Nz53_VALUE = 113;
  /**
   * <code>Nz54 = 114;</code>
   */
  public static final int Nz54_VALUE = 114;
  /**
   * <code>Nz55 = 115;</code>
   */
  public static final int Nz55_VALUE = 115;
  /**
   * <code>Nz56 = 116;</code>
   */
  public static final int Nz56_VALUE = 116;
  /**
   * <code>Nz57 = 117;</code>
   */
  public static final int Nz57_VALUE = 117;
  /**
   * <code>Nz58 = 118;</code>
   */
  public static final int Nz58_VALUE = 118;
  /**
   * <code>Nz60 = 120;</code>
   */
  public static final int Nz60_VALUE = 120;
  /**
   * <code>Nz61 = 121;</code>
   */
  public static final int Nz61_VALUE = 121;
  /**
   * <code>Nz62 = 122;</code>
   */
  public static final int Nz62_VALUE = 122;
  /**
   * <code>Nz63 = 123;</code>
   */
  public static final int Nz63_VALUE = 123;
  /**
   * <code>Nz64 = 124;</code>
   */
  public static final int Nz64_VALUE = 124;
  /**
   * <code>Nz65 = 125;</code>
   */
  public static final int Nz65_VALUE = 125;
  /**
   * <code>Nz66 = 126;</code>
   */
  public static final int Nz66_VALUE = 126;
  /**
   * <code>Nz67 = 127;</code>
   */
  public static final int Nz67_VALUE = 127;
  /**
   * <code>Nz68 = 128;</code>
   */
  public static final int Nz68_VALUE = 128;
  /**
   * <code>Nz69 = 129;</code>
   */
  public static final int Nz69_VALUE = 129;
  /**
   * <code>Nz70 = 130;</code>
   */
  public static final int Nz70_VALUE = 130;
  /**
   * <code>Nz71 = 131;</code>
   */
  public static final int Nz71_VALUE = 131;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FuelName valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FuelName forNumber(int value) {
    switch (value) {
      case 0: return unset;
      case 1: return C1;
      case 2: return C2;
      case 3: return C3;
      case 4: return C4;
      case 5: return C5;
      case 6: return C6;
      case 7: return C7;
      case 11: return D1;
      case 12: return D2;
      case 13: return D1D2;
      case 21: return M1;
      case 22: return M2;
      case 23: return M1M2;
      case 24: return M3;
      case 25: return M4;
      case 26: return M3M4;
      case 31: return O1A;
      case 32: return O1B;
      case 33: return O1AB;
      case 41: return S1;
      case 42: return S2;
      case 43: return S3;
      case 51: return Non;
      case 62: return Nz2;
      case 75: return Nz15;
      case 90: return Nz30;
      case 91: return Nz31;
      case 92: return Nz32;
      case 93: return Nz33;
      case 100: return Nz40;
      case 101: return Nz41;
      case 103: return Nz43;
      case 104: return Nz44;
      case 105: return Nz45;
      case 106: return Nz46;
      case 107: return Nz47;
      case 110: return Nz50;
      case 111: return Nz51;
      case 112: return Nz52;
      case 113: return Nz53;
      case 114: return Nz54;
      case 115: return Nz55;
      case 116: return Nz56;
      case 117: return Nz57;
      case 118: return Nz58;
      case 120: return Nz60;
      case 121: return Nz61;
      case 122: return Nz62;
      case 123: return Nz63;
      case 124: return Nz64;
      case 125: return Nz65;
      case 126: return Nz66;
      case 127: return Nz67;
      case 128: return Nz68;
      case 129: return Nz69;
      case 130: return Nz70;
      case 131: return Nz71;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FuelName>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FuelName> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FuelName>() {
          public FuelName findValueByNumber(int number) {
            return FuelName.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ca.wise.fuel.proto.FuelNames.getDescriptor().getEnumTypes().get(0);
  }

  private static final FuelName[] VALUES = values();

  public static FuelName valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FuelName(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:WISE.FuelProto.FuelName)
}

