// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: isf.proto

package ca.wise.fuel.proto;

/**
 * Protobuf type {@code WISE.FuelProto.IsfM3M4}
 */
public final class IsfM3M4 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.FuelProto.IsfM3M4)
    IsfM3M4OrBuilder {
private static final long serialVersionUID = 0L;
  // Use IsfM3M4.newBuilder() to construct.
  private IsfM3M4(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IsfM3M4() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IsfM3M4();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IsfM3M4(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            msgCase_ = 2;
            msg_ = rawValue;
            break;
          }
          case 26: {
            ca.wise.fuel.proto.IsfM3M4.Parms.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((ca.wise.fuel.proto.IsfM3M4.Parms) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.IsfM3M4.Parms.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.IsfM3M4.Parms) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.fuel.proto.IsfM3M4.class, ca.wise.fuel.proto.IsfM3M4.Builder.class);
  }

  public interface ParmsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.FuelProto.IsfM3M4.Parms)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>string notes = 2 [deprecated = true];</code>
     * @return The notes.
     */
    @java.lang.Deprecated java.lang.String getNotes();
    /**
     * <code>string notes = 2 [deprecated = true];</code>
     * @return The bytes for notes.
     */
    @java.lang.Deprecated com.google.protobuf.ByteString
        getNotesBytes();

    /**
     * <code>.Math.Double a = 3;</code>
     * @return Whether the a field is set.
     */
    boolean hasA();
    /**
     * <code>.Math.Double a = 3;</code>
     * @return The a.
     */
    ca.hss.math.proto.Double getA();
    /**
     * <code>.Math.Double a = 3;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getAOrBuilder();

    /**
     * <code>.Math.Double b = 4;</code>
     * @return Whether the b field is set.
     */
    boolean hasB();
    /**
     * <code>.Math.Double b = 4;</code>
     * @return The b.
     */
    ca.hss.math.proto.Double getB();
    /**
     * <code>.Math.Double b = 4;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getBOrBuilder();

    /**
     * <code>.Math.Double c = 5;</code>
     * @return Whether the c field is set.
     */
    boolean hasC();
    /**
     * <code>.Math.Double c = 5;</code>
     * @return The c.
     */
    ca.hss.math.proto.Double getC();
    /**
     * <code>.Math.Double c = 5;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getCOrBuilder();
  }
  /**
   * Protobuf type {@code WISE.FuelProto.IsfM3M4.Parms}
   */
  public static final class Parms extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.FuelProto.IsfM3M4.Parms)
      ParmsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Parms.newBuilder() to construct.
    private Parms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Parms() {
      notes_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Parms();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Parms(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              notes_ = s;
              break;
            }
            case 26: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (a_ != null) {
                subBuilder = a_.toBuilder();
              }
              a_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(a_);
                a_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (b_ != null) {
                subBuilder = b_.toBuilder();
              }
              b_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(b_);
                b_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (c_ != null) {
                subBuilder = c_.toBuilder();
              }
              c_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(c_);
                c_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_Parms_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_Parms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.fuel.proto.IsfM3M4.Parms.class, ca.wise.fuel.proto.IsfM3M4.Parms.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int NOTES_FIELD_NUMBER = 2;
    private volatile java.lang.Object notes_;
    /**
     * <code>string notes = 2 [deprecated = true];</code>
     * @return The notes.
     */
    @java.lang.Override
    @java.lang.Deprecated public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notes_ = s;
        return s;
      }
    }
    /**
     * <code>string notes = 2 [deprecated = true];</code>
     * @return The bytes for notes.
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int A_FIELD_NUMBER = 3;
    private ca.hss.math.proto.Double a_;
    /**
     * <code>.Math.Double a = 3;</code>
     * @return Whether the a field is set.
     */
    @java.lang.Override
    public boolean hasA() {
      return a_ != null;
    }
    /**
     * <code>.Math.Double a = 3;</code>
     * @return The a.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getA() {
      return a_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : a_;
    }
    /**
     * <code>.Math.Double a = 3;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getAOrBuilder() {
      return getA();
    }

    public static final int B_FIELD_NUMBER = 4;
    private ca.hss.math.proto.Double b_;
    /**
     * <code>.Math.Double b = 4;</code>
     * @return Whether the b field is set.
     */
    @java.lang.Override
    public boolean hasB() {
      return b_ != null;
    }
    /**
     * <code>.Math.Double b = 4;</code>
     * @return The b.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getB() {
      return b_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : b_;
    }
    /**
     * <code>.Math.Double b = 4;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getBOrBuilder() {
      return getB();
    }

    public static final int C_FIELD_NUMBER = 5;
    private ca.hss.math.proto.Double c_;
    /**
     * <code>.Math.Double c = 5;</code>
     * @return Whether the c field is set.
     */
    @java.lang.Override
    public boolean hasC() {
      return c_ != null;
    }
    /**
     * <code>.Math.Double c = 5;</code>
     * @return The c.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getC() {
      return c_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : c_;
    }
    /**
     * <code>.Math.Double c = 5;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getCOrBuilder() {
      return getC();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (!getNotesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, notes_);
      }
      if (a_ != null) {
        output.writeMessage(3, getA());
      }
      if (b_ != null) {
        output.writeMessage(4, getB());
      }
      if (c_ != null) {
        output.writeMessage(5, getC());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (!getNotesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, notes_);
      }
      if (a_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getA());
      }
      if (b_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getB());
      }
      if (c_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getC());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.fuel.proto.IsfM3M4.Parms)) {
        return super.equals(obj);
      }
      ca.wise.fuel.proto.IsfM3M4.Parms other = (ca.wise.fuel.proto.IsfM3M4.Parms) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (!getNotes()
          .equals(other.getNotes())) return false;
      if (hasA() != other.hasA()) return false;
      if (hasA()) {
        if (!getA()
            .equals(other.getA())) return false;
      }
      if (hasB() != other.hasB()) return false;
      if (hasB()) {
        if (!getB()
            .equals(other.getB())) return false;
      }
      if (hasC() != other.hasC()) return false;
      if (hasC()) {
        if (!getC()
            .equals(other.getC())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + NOTES_FIELD_NUMBER;
      hash = (53 * hash) + getNotes().hashCode();
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA().hashCode();
      }
      if (hasB()) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB().hashCode();
      }
      if (hasC()) {
        hash = (37 * hash) + C_FIELD_NUMBER;
        hash = (53 * hash) + getC().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.fuel.proto.IsfM3M4.Parms parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.fuel.proto.IsfM3M4.Parms prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WISE.FuelProto.IsfM3M4.Parms}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.FuelProto.IsfM3M4.Parms)
        ca.wise.fuel.proto.IsfM3M4.ParmsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_Parms_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_Parms_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.fuel.proto.IsfM3M4.Parms.class, ca.wise.fuel.proto.IsfM3M4.Parms.Builder.class);
      }

      // Construct using ca.wise.fuel.proto.IsfM3M4.Parms.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        notes_ = "";

        if (aBuilder_ == null) {
          a_ = null;
        } else {
          a_ = null;
          aBuilder_ = null;
        }
        if (bBuilder_ == null) {
          b_ = null;
        } else {
          b_ = null;
          bBuilder_ = null;
        }
        if (cBuilder_ == null) {
          c_ = null;
        } else {
          c_ = null;
          cBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_Parms_descriptor;
      }

      @java.lang.Override
      public ca.wise.fuel.proto.IsfM3M4.Parms getDefaultInstanceForType() {
        return ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.fuel.proto.IsfM3M4.Parms build() {
        ca.wise.fuel.proto.IsfM3M4.Parms result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.fuel.proto.IsfM3M4.Parms buildPartial() {
        ca.wise.fuel.proto.IsfM3M4.Parms result = new ca.wise.fuel.proto.IsfM3M4.Parms(this);
        result.version_ = version_;
        result.notes_ = notes_;
        if (aBuilder_ == null) {
          result.a_ = a_;
        } else {
          result.a_ = aBuilder_.build();
        }
        if (bBuilder_ == null) {
          result.b_ = b_;
        } else {
          result.b_ = bBuilder_.build();
        }
        if (cBuilder_ == null) {
          result.c_ = c_;
        } else {
          result.c_ = cBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.fuel.proto.IsfM3M4.Parms) {
          return mergeFrom((ca.wise.fuel.proto.IsfM3M4.Parms)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.fuel.proto.IsfM3M4.Parms other) {
        if (other == ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getNotes().isEmpty()) {
          notes_ = other.notes_;
          onChanged();
        }
        if (other.hasA()) {
          mergeA(other.getA());
        }
        if (other.hasB()) {
          mergeB(other.getB());
        }
        if (other.hasC()) {
          mergeC(other.getC());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.fuel.proto.IsfM3M4.Parms parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.fuel.proto.IsfM3M4.Parms) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object notes_ = "";
      /**
       * <code>string notes = 2 [deprecated = true];</code>
       * @return The notes.
       */
      @java.lang.Deprecated public java.lang.String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string notes = 2 [deprecated = true];</code>
       * @return The bytes for notes.
       */
      @java.lang.Deprecated public com.google.protobuf.ByteString
          getNotesBytes() {
        java.lang.Object ref = notes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string notes = 2 [deprecated = true];</code>
       * @param value The notes to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setNotes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        notes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string notes = 2 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearNotes() {
        
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      /**
       * <code>string notes = 2 [deprecated = true];</code>
       * @param value The bytes for notes to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        notes_ = value;
        onChanged();
        return this;
      }

      private ca.hss.math.proto.Double a_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> aBuilder_;
      /**
       * <code>.Math.Double a = 3;</code>
       * @return Whether the a field is set.
       */
      public boolean hasA() {
        return aBuilder_ != null || a_ != null;
      }
      /**
       * <code>.Math.Double a = 3;</code>
       * @return The a.
       */
      public ca.hss.math.proto.Double getA() {
        if (aBuilder_ == null) {
          return a_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : a_;
        } else {
          return aBuilder_.getMessage();
        }
      }
      /**
       * <code>.Math.Double a = 3;</code>
       */
      public Builder setA(ca.hss.math.proto.Double value) {
        if (aBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          a_ = value;
          onChanged();
        } else {
          aBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double a = 3;</code>
       */
      public Builder setA(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (aBuilder_ == null) {
          a_ = builderForValue.build();
          onChanged();
        } else {
          aBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Math.Double a = 3;</code>
       */
      public Builder mergeA(ca.hss.math.proto.Double value) {
        if (aBuilder_ == null) {
          if (a_ != null) {
            a_ =
              ca.hss.math.proto.Double.newBuilder(a_).mergeFrom(value).buildPartial();
          } else {
            a_ = value;
          }
          onChanged();
        } else {
          aBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double a = 3;</code>
       */
      public Builder clearA() {
        if (aBuilder_ == null) {
          a_ = null;
          onChanged();
        } else {
          a_ = null;
          aBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Math.Double a = 3;</code>
       */
      public ca.hss.math.proto.Double.Builder getABuilder() {
        
        onChanged();
        return getAFieldBuilder().getBuilder();
      }
      /**
       * <code>.Math.Double a = 3;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getAOrBuilder() {
        if (aBuilder_ != null) {
          return aBuilder_.getMessageOrBuilder();
        } else {
          return a_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : a_;
        }
      }
      /**
       * <code>.Math.Double a = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getAFieldBuilder() {
        if (aBuilder_ == null) {
          aBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getA(),
                  getParentForChildren(),
                  isClean());
          a_ = null;
        }
        return aBuilder_;
      }

      private ca.hss.math.proto.Double b_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> bBuilder_;
      /**
       * <code>.Math.Double b = 4;</code>
       * @return Whether the b field is set.
       */
      public boolean hasB() {
        return bBuilder_ != null || b_ != null;
      }
      /**
       * <code>.Math.Double b = 4;</code>
       * @return The b.
       */
      public ca.hss.math.proto.Double getB() {
        if (bBuilder_ == null) {
          return b_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : b_;
        } else {
          return bBuilder_.getMessage();
        }
      }
      /**
       * <code>.Math.Double b = 4;</code>
       */
      public Builder setB(ca.hss.math.proto.Double value) {
        if (bBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          b_ = value;
          onChanged();
        } else {
          bBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double b = 4;</code>
       */
      public Builder setB(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (bBuilder_ == null) {
          b_ = builderForValue.build();
          onChanged();
        } else {
          bBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Math.Double b = 4;</code>
       */
      public Builder mergeB(ca.hss.math.proto.Double value) {
        if (bBuilder_ == null) {
          if (b_ != null) {
            b_ =
              ca.hss.math.proto.Double.newBuilder(b_).mergeFrom(value).buildPartial();
          } else {
            b_ = value;
          }
          onChanged();
        } else {
          bBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double b = 4;</code>
       */
      public Builder clearB() {
        if (bBuilder_ == null) {
          b_ = null;
          onChanged();
        } else {
          b_ = null;
          bBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Math.Double b = 4;</code>
       */
      public ca.hss.math.proto.Double.Builder getBBuilder() {
        
        onChanged();
        return getBFieldBuilder().getBuilder();
      }
      /**
       * <code>.Math.Double b = 4;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getBOrBuilder() {
        if (bBuilder_ != null) {
          return bBuilder_.getMessageOrBuilder();
        } else {
          return b_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : b_;
        }
      }
      /**
       * <code>.Math.Double b = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getBFieldBuilder() {
        if (bBuilder_ == null) {
          bBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getB(),
                  getParentForChildren(),
                  isClean());
          b_ = null;
        }
        return bBuilder_;
      }

      private ca.hss.math.proto.Double c_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> cBuilder_;
      /**
       * <code>.Math.Double c = 5;</code>
       * @return Whether the c field is set.
       */
      public boolean hasC() {
        return cBuilder_ != null || c_ != null;
      }
      /**
       * <code>.Math.Double c = 5;</code>
       * @return The c.
       */
      public ca.hss.math.proto.Double getC() {
        if (cBuilder_ == null) {
          return c_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : c_;
        } else {
          return cBuilder_.getMessage();
        }
      }
      /**
       * <code>.Math.Double c = 5;</code>
       */
      public Builder setC(ca.hss.math.proto.Double value) {
        if (cBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          c_ = value;
          onChanged();
        } else {
          cBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double c = 5;</code>
       */
      public Builder setC(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (cBuilder_ == null) {
          c_ = builderForValue.build();
          onChanged();
        } else {
          cBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Math.Double c = 5;</code>
       */
      public Builder mergeC(ca.hss.math.proto.Double value) {
        if (cBuilder_ == null) {
          if (c_ != null) {
            c_ =
              ca.hss.math.proto.Double.newBuilder(c_).mergeFrom(value).buildPartial();
          } else {
            c_ = value;
          }
          onChanged();
        } else {
          cBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double c = 5;</code>
       */
      public Builder clearC() {
        if (cBuilder_ == null) {
          c_ = null;
          onChanged();
        } else {
          c_ = null;
          cBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Math.Double c = 5;</code>
       */
      public ca.hss.math.proto.Double.Builder getCBuilder() {
        
        onChanged();
        return getCFieldBuilder().getBuilder();
      }
      /**
       * <code>.Math.Double c = 5;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getCOrBuilder() {
        if (cBuilder_ != null) {
          return cBuilder_.getMessageOrBuilder();
        } else {
          return c_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : c_;
        }
      }
      /**
       * <code>.Math.Double c = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getCFieldBuilder() {
        if (cBuilder_ == null) {
          cBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getC(),
                  getParentForChildren(),
                  isClean());
          c_ = null;
        }
        return cBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.FuelProto.IsfM3M4.Parms)
    }

    // @@protoc_insertion_point(class_scope:WISE.FuelProto.IsfM3M4.Parms)
    private static final ca.wise.fuel.proto.IsfM3M4.Parms DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.fuel.proto.IsfM3M4.Parms();
    }

    public static ca.wise.fuel.proto.IsfM3M4.Parms getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Parms>
        PARSER = new com.google.protobuf.AbstractParser<Parms>() {
      @java.lang.Override
      public Parms parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Parms(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Parms> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Parms> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.IsfM3M4.Parms getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    DEFAULT(2),
    PARMS(3),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 2: return DEFAULT;
        case 3: return PARMS;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int DEFAULT_FIELD_NUMBER = 2;
  /**
   * <code>.WISE.FuelProto.FuelName default = 2;</code>
   * @return The enum numeric value on the wire for default.
   */
  public int getDefaultValue() {
    if (msgCase_ == 2) {
      return (java.lang.Integer) msg_;
    }
    return 0;
  }
  /**
   * <code>.WISE.FuelProto.FuelName default = 2;</code>
   * @return The default.
   */
  public ca.wise.fuel.proto.FuelName getDefault() {
    if (msgCase_ == 2) {
      @SuppressWarnings("deprecation")
      ca.wise.fuel.proto.FuelName result = ca.wise.fuel.proto.FuelName.valueOf(
          (java.lang.Integer) msg_);
      return result == null ? ca.wise.fuel.proto.FuelName.UNRECOGNIZED : result;
    }
    return ca.wise.fuel.proto.FuelName.unset;
  }

  public static final int PARMS_FIELD_NUMBER = 3;
  /**
   * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
   * @return Whether the parms field is set.
   */
  @java.lang.Override
  public boolean hasParms() {
    return msgCase_ == 3;
  }
  /**
   * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
   * @return The parms.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.IsfM3M4.Parms getParms() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.IsfM3M4.Parms) msg_;
    }
    return ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.IsfM3M4.ParmsOrBuilder getParmsOrBuilder() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.IsfM3M4.Parms) msg_;
    }
    return ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (msgCase_ == 2) {
      output.writeEnum(2, ((java.lang.Integer) msg_));
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (ca.wise.fuel.proto.IsfM3M4.Parms) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ((java.lang.Integer) msg_));
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ca.wise.fuel.proto.IsfM3M4.Parms) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.fuel.proto.IsfM3M4)) {
      return super.equals(obj);
    }
    ca.wise.fuel.proto.IsfM3M4 other = (ca.wise.fuel.proto.IsfM3M4) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 2:
        if (getDefaultValue()
            != other.getDefaultValue()) return false;
        break;
      case 3:
        if (!getParms()
            .equals(other.getParms())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    switch (msgCase_) {
      case 2:
        hash = (37 * hash) + DEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + getDefaultValue();
        break;
      case 3:
        hash = (37 * hash) + PARMS_FIELD_NUMBER;
        hash = (53 * hash) + getParms().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.IsfM3M4 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.fuel.proto.IsfM3M4 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.FuelProto.IsfM3M4}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.FuelProto.IsfM3M4)
      ca.wise.fuel.proto.IsfM3M4OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.fuel.proto.IsfM3M4.class, ca.wise.fuel.proto.IsfM3M4.Builder.class);
    }

    // Construct using ca.wise.fuel.proto.IsfM3M4.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.fuel.proto.Isf.internal_static_WISE_FuelProto_IsfM3M4_descriptor;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.IsfM3M4 getDefaultInstanceForType() {
      return ca.wise.fuel.proto.IsfM3M4.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.fuel.proto.IsfM3M4 build() {
      ca.wise.fuel.proto.IsfM3M4 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.IsfM3M4 buildPartial() {
      ca.wise.fuel.proto.IsfM3M4 result = new ca.wise.fuel.proto.IsfM3M4(this);
      result.version_ = version_;
      if (msgCase_ == 2) {
        result.msg_ = msg_;
      }
      if (msgCase_ == 3) {
        if (parmsBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = parmsBuilder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.fuel.proto.IsfM3M4) {
        return mergeFrom((ca.wise.fuel.proto.IsfM3M4)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.fuel.proto.IsfM3M4 other) {
      if (other == ca.wise.fuel.proto.IsfM3M4.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      switch (other.getMsgCase()) {
        case DEFAULT: {
          setDefaultValue(other.getDefaultValue());
          break;
        }
        case PARMS: {
          mergeParms(other.getParms());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.fuel.proto.IsfM3M4 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.fuel.proto.IsfM3M4) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @return The enum numeric value on the wire for default.
     */
    @java.lang.Override
    public int getDefaultValue() {
      if (msgCase_ == 2) {
        return ((java.lang.Integer) msg_).intValue();
      }
      return 0;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @param value The enum numeric value on the wire for default to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultValue(int value) {
      msgCase_ = 2;
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @return The default.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.FuelName getDefault() {
      if (msgCase_ == 2) {
        @SuppressWarnings("deprecation")
        ca.wise.fuel.proto.FuelName result = ca.wise.fuel.proto.FuelName.valueOf(
            (java.lang.Integer) msg_);
        return result == null ? ca.wise.fuel.proto.FuelName.UNRECOGNIZED : result;
      }
      return ca.wise.fuel.proto.FuelName.unset;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @param value The default to set.
     * @return This builder for chaining.
     */
    public Builder setDefault(ca.wise.fuel.proto.FuelName value) {
      if (value == null) {
        throw new NullPointerException();
      }
      msgCase_ = 2;
      msg_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefault() {
      if (msgCase_ == 2) {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.IsfM3M4.Parms, ca.wise.fuel.proto.IsfM3M4.Parms.Builder, ca.wise.fuel.proto.IsfM3M4.ParmsOrBuilder> parmsBuilder_;
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     * @return Whether the parms field is set.
     */
    @java.lang.Override
    public boolean hasParms() {
      return msgCase_ == 3;
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     * @return The parms.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.IsfM3M4.Parms getParms() {
      if (parmsBuilder_ == null) {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.IsfM3M4.Parms) msg_;
        }
        return ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return parmsBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     */
    public Builder setParms(ca.wise.fuel.proto.IsfM3M4.Parms value) {
      if (parmsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        parmsBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     */
    public Builder setParms(
        ca.wise.fuel.proto.IsfM3M4.Parms.Builder builderForValue) {
      if (parmsBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        parmsBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     */
    public Builder mergeParms(ca.wise.fuel.proto.IsfM3M4.Parms value) {
      if (parmsBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.IsfM3M4.Parms.newBuilder((ca.wise.fuel.proto.IsfM3M4.Parms) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          parmsBuilder_.mergeFrom(value);
        }
        parmsBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     */
    public Builder clearParms() {
      if (parmsBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        parmsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     */
    public ca.wise.fuel.proto.IsfM3M4.Parms.Builder getParmsBuilder() {
      return getParmsFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.IsfM3M4.ParmsOrBuilder getParmsOrBuilder() {
      if ((msgCase_ == 3) && (parmsBuilder_ != null)) {
        return parmsBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.IsfM3M4.Parms) msg_;
        }
        return ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.IsfM3M4.Parms parms = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.IsfM3M4.Parms, ca.wise.fuel.proto.IsfM3M4.Parms.Builder, ca.wise.fuel.proto.IsfM3M4.ParmsOrBuilder> 
        getParmsFieldBuilder() {
      if (parmsBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = ca.wise.fuel.proto.IsfM3M4.Parms.getDefaultInstance();
        }
        parmsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.IsfM3M4.Parms, ca.wise.fuel.proto.IsfM3M4.Parms.Builder, ca.wise.fuel.proto.IsfM3M4.ParmsOrBuilder>(
                (ca.wise.fuel.proto.IsfM3M4.Parms) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return parmsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.FuelProto.IsfM3M4)
  }

  // @@protoc_insertion_point(class_scope:WISE.FuelProto.IsfM3M4)
  private static final ca.wise.fuel.proto.IsfM3M4 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.fuel.proto.IsfM3M4();
  }

  public static ca.wise.fuel.proto.IsfM3M4 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IsfM3M4>
      PARSER = new com.google.protobuf.AbstractParser<IsfM3M4>() {
    @java.lang.Override
    public IsfM3M4 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IsfM3M4(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IsfM3M4> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IsfM3M4> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.fuel.proto.IsfM3M4 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

