// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccwfgmFuel.proto

package ca.wise.fuel.proto;

/**
 * Protobuf type {@code WISE.FuelProto.LbAttribute}
 */
public final class LbAttribute extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.FuelProto.LbAttribute)
    LbAttributeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LbAttribute.newBuilder() to construct.
  private LbAttribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LbAttribute() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LbAttribute();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LbAttribute(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            commonField_ = input.readInt64();
            break;
          }
          case 26: {
            ca.wise.fuel.proto.LbC1.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((ca.wise.fuel.proto.LbC1) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.LbC1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.LbC1) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          case 34: {
            ca.wise.fuel.proto.LbO1.Builder subBuilder = null;
            if (msgCase_ == 4) {
              subBuilder = ((ca.wise.fuel.proto.LbO1) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.LbO1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.LbO1) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_LbAttribute_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_LbAttribute_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.fuel.proto.LbAttribute.class, ca.wise.fuel.proto.LbAttribute.Builder.class);
  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    C1(3),
    O1(4),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 3: return C1;
        case 4: return O1;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int COMMONFIELD_FIELD_NUMBER = 2;
  private long commonField_;
  /**
   * <code>int64 commonField = 2 [deprecated = true];</code>
   * @return The commonField.
   */
  @java.lang.Override
  @java.lang.Deprecated public long getCommonField() {
    return commonField_;
  }

  public static final int C1_FIELD_NUMBER = 3;
  /**
   * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
   * @return Whether the c1 field is set.
   */
  @java.lang.Override
  public boolean hasC1() {
    return msgCase_ == 3;
  }
  /**
   * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
   * @return The c1.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.LbC1 getC1() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.LbC1) msg_;
    }
    return ca.wise.fuel.proto.LbC1.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.LbC1OrBuilder getC1OrBuilder() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.LbC1) msg_;
    }
    return ca.wise.fuel.proto.LbC1.getDefaultInstance();
  }

  public static final int O1_FIELD_NUMBER = 4;
  /**
   * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
   * @return Whether the o1 field is set.
   */
  @java.lang.Override
  public boolean hasO1() {
    return msgCase_ == 4;
  }
  /**
   * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
   * @return The o1.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.LbO1 getO1() {
    if (msgCase_ == 4) {
       return (ca.wise.fuel.proto.LbO1) msg_;
    }
    return ca.wise.fuel.proto.LbO1.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.LbO1OrBuilder getO1OrBuilder() {
    if (msgCase_ == 4) {
       return (ca.wise.fuel.proto.LbO1) msg_;
    }
    return ca.wise.fuel.proto.LbO1.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (commonField_ != 0L) {
      output.writeInt64(2, commonField_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (ca.wise.fuel.proto.LbC1) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (ca.wise.fuel.proto.LbO1) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (commonField_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, commonField_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ca.wise.fuel.proto.LbC1) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ca.wise.fuel.proto.LbO1) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.fuel.proto.LbAttribute)) {
      return super.equals(obj);
    }
    ca.wise.fuel.proto.LbAttribute other = (ca.wise.fuel.proto.LbAttribute) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (getCommonField()
        != other.getCommonField()) return false;
    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 3:
        if (!getC1()
            .equals(other.getC1())) return false;
        break;
      case 4:
        if (!getO1()
            .equals(other.getO1())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + COMMONFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommonField());
    switch (msgCase_) {
      case 3:
        hash = (37 * hash) + C1_FIELD_NUMBER;
        hash = (53 * hash) + getC1().hashCode();
        break;
      case 4:
        hash = (37 * hash) + O1_FIELD_NUMBER;
        hash = (53 * hash) + getO1().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbAttribute parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.LbAttribute parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.LbAttribute parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.fuel.proto.LbAttribute prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.FuelProto.LbAttribute}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.FuelProto.LbAttribute)
      ca.wise.fuel.proto.LbAttributeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_LbAttribute_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_LbAttribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.fuel.proto.LbAttribute.class, ca.wise.fuel.proto.LbAttribute.Builder.class);
    }

    // Construct using ca.wise.fuel.proto.LbAttribute.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      commonField_ = 0L;

      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_LbAttribute_descriptor;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.LbAttribute getDefaultInstanceForType() {
      return ca.wise.fuel.proto.LbAttribute.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.fuel.proto.LbAttribute build() {
      ca.wise.fuel.proto.LbAttribute result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.LbAttribute buildPartial() {
      ca.wise.fuel.proto.LbAttribute result = new ca.wise.fuel.proto.LbAttribute(this);
      result.version_ = version_;
      result.commonField_ = commonField_;
      if (msgCase_ == 3) {
        if (c1Builder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = c1Builder_.build();
        }
      }
      if (msgCase_ == 4) {
        if (o1Builder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = o1Builder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.fuel.proto.LbAttribute) {
        return mergeFrom((ca.wise.fuel.proto.LbAttribute)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.fuel.proto.LbAttribute other) {
      if (other == ca.wise.fuel.proto.LbAttribute.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getCommonField() != 0L) {
        setCommonField(other.getCommonField());
      }
      switch (other.getMsgCase()) {
        case C1: {
          mergeC1(other.getC1());
          break;
        }
        case O1: {
          mergeO1(other.getO1());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.fuel.proto.LbAttribute parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.fuel.proto.LbAttribute) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private long commonField_ ;
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @return The commonField.
     */
    @java.lang.Override
    @java.lang.Deprecated public long getCommonField() {
      return commonField_;
    }
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @param value The commonField to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setCommonField(long value) {
      
      commonField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearCommonField() {
      
      commonField_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.LbC1, ca.wise.fuel.proto.LbC1.Builder, ca.wise.fuel.proto.LbC1OrBuilder> c1Builder_;
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     * @return Whether the c1 field is set.
     */
    @java.lang.Override
    public boolean hasC1() {
      return msgCase_ == 3;
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     * @return The c1.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.LbC1 getC1() {
      if (c1Builder_ == null) {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.LbC1) msg_;
        }
        return ca.wise.fuel.proto.LbC1.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return c1Builder_.getMessage();
        }
        return ca.wise.fuel.proto.LbC1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     */
    public Builder setC1(ca.wise.fuel.proto.LbC1 value) {
      if (c1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        c1Builder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     */
    public Builder setC1(
        ca.wise.fuel.proto.LbC1.Builder builderForValue) {
      if (c1Builder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        c1Builder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     */
    public Builder mergeC1(ca.wise.fuel.proto.LbC1 value) {
      if (c1Builder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != ca.wise.fuel.proto.LbC1.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.LbC1.newBuilder((ca.wise.fuel.proto.LbC1) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          c1Builder_.mergeFrom(value);
        }
        c1Builder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     */
    public Builder clearC1() {
      if (c1Builder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        c1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     */
    public ca.wise.fuel.proto.LbC1.Builder getC1Builder() {
      return getC1FieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.LbC1OrBuilder getC1OrBuilder() {
      if ((msgCase_ == 3) && (c1Builder_ != null)) {
        return c1Builder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.LbC1) msg_;
        }
        return ca.wise.fuel.proto.LbC1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.LbC1, ca.wise.fuel.proto.LbC1.Builder, ca.wise.fuel.proto.LbC1OrBuilder> 
        getC1FieldBuilder() {
      if (c1Builder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = ca.wise.fuel.proto.LbC1.getDefaultInstance();
        }
        c1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.LbC1, ca.wise.fuel.proto.LbC1.Builder, ca.wise.fuel.proto.LbC1OrBuilder>(
                (ca.wise.fuel.proto.LbC1) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return c1Builder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.LbO1, ca.wise.fuel.proto.LbO1.Builder, ca.wise.fuel.proto.LbO1OrBuilder> o1Builder_;
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     * @return Whether the o1 field is set.
     */
    @java.lang.Override
    public boolean hasO1() {
      return msgCase_ == 4;
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     * @return The o1.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.LbO1 getO1() {
      if (o1Builder_ == null) {
        if (msgCase_ == 4) {
          return (ca.wise.fuel.proto.LbO1) msg_;
        }
        return ca.wise.fuel.proto.LbO1.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return o1Builder_.getMessage();
        }
        return ca.wise.fuel.proto.LbO1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     */
    public Builder setO1(ca.wise.fuel.proto.LbO1 value) {
      if (o1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        o1Builder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     */
    public Builder setO1(
        ca.wise.fuel.proto.LbO1.Builder builderForValue) {
      if (o1Builder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        o1Builder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     */
    public Builder mergeO1(ca.wise.fuel.proto.LbO1 value) {
      if (o1Builder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != ca.wise.fuel.proto.LbO1.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.LbO1.newBuilder((ca.wise.fuel.proto.LbO1) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          o1Builder_.mergeFrom(value);
        }
        o1Builder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     */
    public Builder clearO1() {
      if (o1Builder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        o1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     */
    public ca.wise.fuel.proto.LbO1.Builder getO1Builder() {
      return getO1FieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.LbO1OrBuilder getO1OrBuilder() {
      if ((msgCase_ == 4) && (o1Builder_ != null)) {
        return o1Builder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (ca.wise.fuel.proto.LbO1) msg_;
        }
        return ca.wise.fuel.proto.LbO1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.LbO1, ca.wise.fuel.proto.LbO1.Builder, ca.wise.fuel.proto.LbO1OrBuilder> 
        getO1FieldBuilder() {
      if (o1Builder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = ca.wise.fuel.proto.LbO1.getDefaultInstance();
        }
        o1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.LbO1, ca.wise.fuel.proto.LbO1.Builder, ca.wise.fuel.proto.LbO1OrBuilder>(
                (ca.wise.fuel.proto.LbO1) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();;
      return o1Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.FuelProto.LbAttribute)
  }

  // @@protoc_insertion_point(class_scope:WISE.FuelProto.LbAttribute)
  private static final ca.wise.fuel.proto.LbAttribute DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.fuel.proto.LbAttribute();
  }

  public static ca.wise.fuel.proto.LbAttribute getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LbAttribute>
      PARSER = new com.google.protobuf.AbstractParser<LbAttribute>() {
    @java.lang.Override
    public LbAttribute parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LbAttribute(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LbAttribute> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LbAttribute> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.fuel.proto.LbAttribute getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

