// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccwfgmFuel.proto

package ca.wise.fuel.proto;

public interface LbAttributeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.FuelProto.LbAttribute)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>int64 commonField = 2 [deprecated = true];</code>
   * @return The commonField.
   */
  @java.lang.Deprecated long getCommonField();

  /**
   * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
   * @return Whether the c1 field is set.
   */
  boolean hasC1();
  /**
   * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
   * @return The c1.
   */
  ca.wise.fuel.proto.LbC1 getC1();
  /**
   * <code>.WISE.FuelProto.LbC1 c1 = 3;</code>
   */
  ca.wise.fuel.proto.LbC1OrBuilder getC1OrBuilder();

  /**
   * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
   * @return Whether the o1 field is set.
   */
  boolean hasO1();
  /**
   * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
   * @return The o1.
   */
  ca.wise.fuel.proto.LbO1 getO1();
  /**
   * <code>.WISE.FuelProto.LbO1 o1 = 4;</code>
   */
  ca.wise.fuel.proto.LbO1OrBuilder getO1OrBuilder();

  public ca.wise.fuel.proto.LbAttribute.MsgCase getMsgCase();
}
