// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lb.proto

package ca.wise.fuel.proto;

/**
 * Protobuf type {@code WISE.FuelProto.LbC1}
 */
public final class LbC1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.FuelProto.LbC1)
    LbC1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use LbC1.newBuilder() to construct.
  private LbC1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LbC1() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LbC1();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LbC1(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            msgCase_ = 2;
            msg_ = rawValue;
            break;
          }
          case 26: {
            ca.wise.fuel.proto.LbC1.Parms.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((ca.wise.fuel.proto.LbC1.Parms) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.LbC1.Parms.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.LbC1.Parms) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.fuel.proto.LbC1.class, ca.wise.fuel.proto.LbC1.Builder.class);
  }

  public interface ParmsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.FuelProto.LbC1.Parms)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>.Math.Double init = 2;</code>
     * @return Whether the init field is set.
     */
    boolean hasInit();
    /**
     * <code>.Math.Double init = 2;</code>
     * @return The init.
     */
    ca.hss.math.proto.Double getInit();
    /**
     * <code>.Math.Double init = 2;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getInitOrBuilder();

    /**
     * <code>.Math.Double multiplier = 3;</code>
     * @return Whether the multiplier field is set.
     */
    boolean hasMultiplier();
    /**
     * <code>.Math.Double multiplier = 3;</code>
     * @return The multiplier.
     */
    ca.hss.math.proto.Double getMultiplier();
    /**
     * <code>.Math.Double multiplier = 3;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getMultiplierOrBuilder();

    /**
     * <code>.Math.Double expMultiplier = 4;</code>
     * @return Whether the expMultiplier field is set.
     */
    boolean hasExpMultiplier();
    /**
     * <code>.Math.Double expMultiplier = 4;</code>
     * @return The expMultiplier.
     */
    ca.hss.math.proto.Double getExpMultiplier();
    /**
     * <code>.Math.Double expMultiplier = 4;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getExpMultiplierOrBuilder();

    /**
     * <code>.Math.Double power = 5;</code>
     * @return Whether the power field is set.
     */
    boolean hasPower();
    /**
     * <code>.Math.Double power = 5;</code>
     * @return The power.
     */
    ca.hss.math.proto.Double getPower();
    /**
     * <code>.Math.Double power = 5;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getPowerOrBuilder();
  }
  /**
   * Protobuf type {@code WISE.FuelProto.LbC1.Parms}
   */
  public static final class Parms extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.FuelProto.LbC1.Parms)
      ParmsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Parms.newBuilder() to construct.
    private Parms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Parms() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Parms();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Parms(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 18: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (init_ != null) {
                subBuilder = init_.toBuilder();
              }
              init_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(init_);
                init_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (multiplier_ != null) {
                subBuilder = multiplier_.toBuilder();
              }
              multiplier_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(multiplier_);
                multiplier_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (expMultiplier_ != null) {
                subBuilder = expMultiplier_.toBuilder();
              }
              expMultiplier_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(expMultiplier_);
                expMultiplier_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (power_ != null) {
                subBuilder = power_.toBuilder();
              }
              power_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(power_);
                power_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_Parms_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_Parms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.fuel.proto.LbC1.Parms.class, ca.wise.fuel.proto.LbC1.Parms.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int INIT_FIELD_NUMBER = 2;
    private ca.hss.math.proto.Double init_;
    /**
     * <code>.Math.Double init = 2;</code>
     * @return Whether the init field is set.
     */
    @java.lang.Override
    public boolean hasInit() {
      return init_ != null;
    }
    /**
     * <code>.Math.Double init = 2;</code>
     * @return The init.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getInit() {
      return init_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : init_;
    }
    /**
     * <code>.Math.Double init = 2;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getInitOrBuilder() {
      return getInit();
    }

    public static final int MULTIPLIER_FIELD_NUMBER = 3;
    private ca.hss.math.proto.Double multiplier_;
    /**
     * <code>.Math.Double multiplier = 3;</code>
     * @return Whether the multiplier field is set.
     */
    @java.lang.Override
    public boolean hasMultiplier() {
      return multiplier_ != null;
    }
    /**
     * <code>.Math.Double multiplier = 3;</code>
     * @return The multiplier.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getMultiplier() {
      return multiplier_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : multiplier_;
    }
    /**
     * <code>.Math.Double multiplier = 3;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getMultiplierOrBuilder() {
      return getMultiplier();
    }

    public static final int EXPMULTIPLIER_FIELD_NUMBER = 4;
    private ca.hss.math.proto.Double expMultiplier_;
    /**
     * <code>.Math.Double expMultiplier = 4;</code>
     * @return Whether the expMultiplier field is set.
     */
    @java.lang.Override
    public boolean hasExpMultiplier() {
      return expMultiplier_ != null;
    }
    /**
     * <code>.Math.Double expMultiplier = 4;</code>
     * @return The expMultiplier.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getExpMultiplier() {
      return expMultiplier_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : expMultiplier_;
    }
    /**
     * <code>.Math.Double expMultiplier = 4;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getExpMultiplierOrBuilder() {
      return getExpMultiplier();
    }

    public static final int POWER_FIELD_NUMBER = 5;
    private ca.hss.math.proto.Double power_;
    /**
     * <code>.Math.Double power = 5;</code>
     * @return Whether the power field is set.
     */
    @java.lang.Override
    public boolean hasPower() {
      return power_ != null;
    }
    /**
     * <code>.Math.Double power = 5;</code>
     * @return The power.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getPower() {
      return power_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : power_;
    }
    /**
     * <code>.Math.Double power = 5;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getPowerOrBuilder() {
      return getPower();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (init_ != null) {
        output.writeMessage(2, getInit());
      }
      if (multiplier_ != null) {
        output.writeMessage(3, getMultiplier());
      }
      if (expMultiplier_ != null) {
        output.writeMessage(4, getExpMultiplier());
      }
      if (power_ != null) {
        output.writeMessage(5, getPower());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (init_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getInit());
      }
      if (multiplier_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMultiplier());
      }
      if (expMultiplier_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getExpMultiplier());
      }
      if (power_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPower());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.fuel.proto.LbC1.Parms)) {
        return super.equals(obj);
      }
      ca.wise.fuel.proto.LbC1.Parms other = (ca.wise.fuel.proto.LbC1.Parms) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (hasInit() != other.hasInit()) return false;
      if (hasInit()) {
        if (!getInit()
            .equals(other.getInit())) return false;
      }
      if (hasMultiplier() != other.hasMultiplier()) return false;
      if (hasMultiplier()) {
        if (!getMultiplier()
            .equals(other.getMultiplier())) return false;
      }
      if (hasExpMultiplier() != other.hasExpMultiplier()) return false;
      if (hasExpMultiplier()) {
        if (!getExpMultiplier()
            .equals(other.getExpMultiplier())) return false;
      }
      if (hasPower() != other.hasPower()) return false;
      if (hasPower()) {
        if (!getPower()
            .equals(other.getPower())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      if (hasInit()) {
        hash = (37 * hash) + INIT_FIELD_NUMBER;
        hash = (53 * hash) + getInit().hashCode();
      }
      if (hasMultiplier()) {
        hash = (37 * hash) + MULTIPLIER_FIELD_NUMBER;
        hash = (53 * hash) + getMultiplier().hashCode();
      }
      if (hasExpMultiplier()) {
        hash = (37 * hash) + EXPMULTIPLIER_FIELD_NUMBER;
        hash = (53 * hash) + getExpMultiplier().hashCode();
      }
      if (hasPower()) {
        hash = (37 * hash) + POWER_FIELD_NUMBER;
        hash = (53 * hash) + getPower().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.fuel.proto.LbC1.Parms parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.fuel.proto.LbC1.Parms prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WISE.FuelProto.LbC1.Parms}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.FuelProto.LbC1.Parms)
        ca.wise.fuel.proto.LbC1.ParmsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_Parms_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_Parms_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.fuel.proto.LbC1.Parms.class, ca.wise.fuel.proto.LbC1.Parms.Builder.class);
      }

      // Construct using ca.wise.fuel.proto.LbC1.Parms.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        if (initBuilder_ == null) {
          init_ = null;
        } else {
          init_ = null;
          initBuilder_ = null;
        }
        if (multiplierBuilder_ == null) {
          multiplier_ = null;
        } else {
          multiplier_ = null;
          multiplierBuilder_ = null;
        }
        if (expMultiplierBuilder_ == null) {
          expMultiplier_ = null;
        } else {
          expMultiplier_ = null;
          expMultiplierBuilder_ = null;
        }
        if (powerBuilder_ == null) {
          power_ = null;
        } else {
          power_ = null;
          powerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_Parms_descriptor;
      }

      @java.lang.Override
      public ca.wise.fuel.proto.LbC1.Parms getDefaultInstanceForType() {
        return ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.fuel.proto.LbC1.Parms build() {
        ca.wise.fuel.proto.LbC1.Parms result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.fuel.proto.LbC1.Parms buildPartial() {
        ca.wise.fuel.proto.LbC1.Parms result = new ca.wise.fuel.proto.LbC1.Parms(this);
        result.version_ = version_;
        if (initBuilder_ == null) {
          result.init_ = init_;
        } else {
          result.init_ = initBuilder_.build();
        }
        if (multiplierBuilder_ == null) {
          result.multiplier_ = multiplier_;
        } else {
          result.multiplier_ = multiplierBuilder_.build();
        }
        if (expMultiplierBuilder_ == null) {
          result.expMultiplier_ = expMultiplier_;
        } else {
          result.expMultiplier_ = expMultiplierBuilder_.build();
        }
        if (powerBuilder_ == null) {
          result.power_ = power_;
        } else {
          result.power_ = powerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.fuel.proto.LbC1.Parms) {
          return mergeFrom((ca.wise.fuel.proto.LbC1.Parms)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.fuel.proto.LbC1.Parms other) {
        if (other == ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.hasInit()) {
          mergeInit(other.getInit());
        }
        if (other.hasMultiplier()) {
          mergeMultiplier(other.getMultiplier());
        }
        if (other.hasExpMultiplier()) {
          mergeExpMultiplier(other.getExpMultiplier());
        }
        if (other.hasPower()) {
          mergePower(other.getPower());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.fuel.proto.LbC1.Parms parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.fuel.proto.LbC1.Parms) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private ca.hss.math.proto.Double init_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> initBuilder_;
      /**
       * <code>.Math.Double init = 2;</code>
       * @return Whether the init field is set.
       */
      public boolean hasInit() {
        return initBuilder_ != null || init_ != null;
      }
      /**
       * <code>.Math.Double init = 2;</code>
       * @return The init.
       */
      public ca.hss.math.proto.Double getInit() {
        if (initBuilder_ == null) {
          return init_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : init_;
        } else {
          return initBuilder_.getMessage();
        }
      }
      /**
       * <code>.Math.Double init = 2;</code>
       */
      public Builder setInit(ca.hss.math.proto.Double value) {
        if (initBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          init_ = value;
          onChanged();
        } else {
          initBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double init = 2;</code>
       */
      public Builder setInit(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (initBuilder_ == null) {
          init_ = builderForValue.build();
          onChanged();
        } else {
          initBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Math.Double init = 2;</code>
       */
      public Builder mergeInit(ca.hss.math.proto.Double value) {
        if (initBuilder_ == null) {
          if (init_ != null) {
            init_ =
              ca.hss.math.proto.Double.newBuilder(init_).mergeFrom(value).buildPartial();
          } else {
            init_ = value;
          }
          onChanged();
        } else {
          initBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double init = 2;</code>
       */
      public Builder clearInit() {
        if (initBuilder_ == null) {
          init_ = null;
          onChanged();
        } else {
          init_ = null;
          initBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Math.Double init = 2;</code>
       */
      public ca.hss.math.proto.Double.Builder getInitBuilder() {
        
        onChanged();
        return getInitFieldBuilder().getBuilder();
      }
      /**
       * <code>.Math.Double init = 2;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getInitOrBuilder() {
        if (initBuilder_ != null) {
          return initBuilder_.getMessageOrBuilder();
        } else {
          return init_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : init_;
        }
      }
      /**
       * <code>.Math.Double init = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getInitFieldBuilder() {
        if (initBuilder_ == null) {
          initBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getInit(),
                  getParentForChildren(),
                  isClean());
          init_ = null;
        }
        return initBuilder_;
      }

      private ca.hss.math.proto.Double multiplier_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> multiplierBuilder_;
      /**
       * <code>.Math.Double multiplier = 3;</code>
       * @return Whether the multiplier field is set.
       */
      public boolean hasMultiplier() {
        return multiplierBuilder_ != null || multiplier_ != null;
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       * @return The multiplier.
       */
      public ca.hss.math.proto.Double getMultiplier() {
        if (multiplierBuilder_ == null) {
          return multiplier_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : multiplier_;
        } else {
          return multiplierBuilder_.getMessage();
        }
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       */
      public Builder setMultiplier(ca.hss.math.proto.Double value) {
        if (multiplierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          multiplier_ = value;
          onChanged();
        } else {
          multiplierBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       */
      public Builder setMultiplier(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (multiplierBuilder_ == null) {
          multiplier_ = builderForValue.build();
          onChanged();
        } else {
          multiplierBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       */
      public Builder mergeMultiplier(ca.hss.math.proto.Double value) {
        if (multiplierBuilder_ == null) {
          if (multiplier_ != null) {
            multiplier_ =
              ca.hss.math.proto.Double.newBuilder(multiplier_).mergeFrom(value).buildPartial();
          } else {
            multiplier_ = value;
          }
          onChanged();
        } else {
          multiplierBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       */
      public Builder clearMultiplier() {
        if (multiplierBuilder_ == null) {
          multiplier_ = null;
          onChanged();
        } else {
          multiplier_ = null;
          multiplierBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       */
      public ca.hss.math.proto.Double.Builder getMultiplierBuilder() {
        
        onChanged();
        return getMultiplierFieldBuilder().getBuilder();
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getMultiplierOrBuilder() {
        if (multiplierBuilder_ != null) {
          return multiplierBuilder_.getMessageOrBuilder();
        } else {
          return multiplier_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : multiplier_;
        }
      }
      /**
       * <code>.Math.Double multiplier = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getMultiplierFieldBuilder() {
        if (multiplierBuilder_ == null) {
          multiplierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getMultiplier(),
                  getParentForChildren(),
                  isClean());
          multiplier_ = null;
        }
        return multiplierBuilder_;
      }

      private ca.hss.math.proto.Double expMultiplier_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> expMultiplierBuilder_;
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       * @return Whether the expMultiplier field is set.
       */
      public boolean hasExpMultiplier() {
        return expMultiplierBuilder_ != null || expMultiplier_ != null;
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       * @return The expMultiplier.
       */
      public ca.hss.math.proto.Double getExpMultiplier() {
        if (expMultiplierBuilder_ == null) {
          return expMultiplier_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : expMultiplier_;
        } else {
          return expMultiplierBuilder_.getMessage();
        }
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       */
      public Builder setExpMultiplier(ca.hss.math.proto.Double value) {
        if (expMultiplierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          expMultiplier_ = value;
          onChanged();
        } else {
          expMultiplierBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       */
      public Builder setExpMultiplier(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (expMultiplierBuilder_ == null) {
          expMultiplier_ = builderForValue.build();
          onChanged();
        } else {
          expMultiplierBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       */
      public Builder mergeExpMultiplier(ca.hss.math.proto.Double value) {
        if (expMultiplierBuilder_ == null) {
          if (expMultiplier_ != null) {
            expMultiplier_ =
              ca.hss.math.proto.Double.newBuilder(expMultiplier_).mergeFrom(value).buildPartial();
          } else {
            expMultiplier_ = value;
          }
          onChanged();
        } else {
          expMultiplierBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       */
      public Builder clearExpMultiplier() {
        if (expMultiplierBuilder_ == null) {
          expMultiplier_ = null;
          onChanged();
        } else {
          expMultiplier_ = null;
          expMultiplierBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       */
      public ca.hss.math.proto.Double.Builder getExpMultiplierBuilder() {
        
        onChanged();
        return getExpMultiplierFieldBuilder().getBuilder();
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getExpMultiplierOrBuilder() {
        if (expMultiplierBuilder_ != null) {
          return expMultiplierBuilder_.getMessageOrBuilder();
        } else {
          return expMultiplier_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : expMultiplier_;
        }
      }
      /**
       * <code>.Math.Double expMultiplier = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getExpMultiplierFieldBuilder() {
        if (expMultiplierBuilder_ == null) {
          expMultiplierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getExpMultiplier(),
                  getParentForChildren(),
                  isClean());
          expMultiplier_ = null;
        }
        return expMultiplierBuilder_;
      }

      private ca.hss.math.proto.Double power_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> powerBuilder_;
      /**
       * <code>.Math.Double power = 5;</code>
       * @return Whether the power field is set.
       */
      public boolean hasPower() {
        return powerBuilder_ != null || power_ != null;
      }
      /**
       * <code>.Math.Double power = 5;</code>
       * @return The power.
       */
      public ca.hss.math.proto.Double getPower() {
        if (powerBuilder_ == null) {
          return power_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : power_;
        } else {
          return powerBuilder_.getMessage();
        }
      }
      /**
       * <code>.Math.Double power = 5;</code>
       */
      public Builder setPower(ca.hss.math.proto.Double value) {
        if (powerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          power_ = value;
          onChanged();
        } else {
          powerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double power = 5;</code>
       */
      public Builder setPower(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (powerBuilder_ == null) {
          power_ = builderForValue.build();
          onChanged();
        } else {
          powerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Math.Double power = 5;</code>
       */
      public Builder mergePower(ca.hss.math.proto.Double value) {
        if (powerBuilder_ == null) {
          if (power_ != null) {
            power_ =
              ca.hss.math.proto.Double.newBuilder(power_).mergeFrom(value).buildPartial();
          } else {
            power_ = value;
          }
          onChanged();
        } else {
          powerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Math.Double power = 5;</code>
       */
      public Builder clearPower() {
        if (powerBuilder_ == null) {
          power_ = null;
          onChanged();
        } else {
          power_ = null;
          powerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Math.Double power = 5;</code>
       */
      public ca.hss.math.proto.Double.Builder getPowerBuilder() {
        
        onChanged();
        return getPowerFieldBuilder().getBuilder();
      }
      /**
       * <code>.Math.Double power = 5;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getPowerOrBuilder() {
        if (powerBuilder_ != null) {
          return powerBuilder_.getMessageOrBuilder();
        } else {
          return power_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : power_;
        }
      }
      /**
       * <code>.Math.Double power = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getPowerFieldBuilder() {
        if (powerBuilder_ == null) {
          powerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getPower(),
                  getParentForChildren(),
                  isClean());
          power_ = null;
        }
        return powerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.FuelProto.LbC1.Parms)
    }

    // @@protoc_insertion_point(class_scope:WISE.FuelProto.LbC1.Parms)
    private static final ca.wise.fuel.proto.LbC1.Parms DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.fuel.proto.LbC1.Parms();
    }

    public static ca.wise.fuel.proto.LbC1.Parms getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Parms>
        PARSER = new com.google.protobuf.AbstractParser<Parms>() {
      @java.lang.Override
      public Parms parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Parms(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Parms> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Parms> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.LbC1.Parms getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    DEFAULT(2),
    PARMS(3),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 2: return DEFAULT;
        case 3: return PARMS;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int DEFAULT_FIELD_NUMBER = 2;
  /**
   * <code>.WISE.FuelProto.FuelName default = 2;</code>
   * @return The enum numeric value on the wire for default.
   */
  public int getDefaultValue() {
    if (msgCase_ == 2) {
      return (java.lang.Integer) msg_;
    }
    return 0;
  }
  /**
   * <code>.WISE.FuelProto.FuelName default = 2;</code>
   * @return The default.
   */
  public ca.wise.fuel.proto.FuelName getDefault() {
    if (msgCase_ == 2) {
      @SuppressWarnings("deprecation")
      ca.wise.fuel.proto.FuelName result = ca.wise.fuel.proto.FuelName.valueOf(
          (java.lang.Integer) msg_);
      return result == null ? ca.wise.fuel.proto.FuelName.UNRECOGNIZED : result;
    }
    return ca.wise.fuel.proto.FuelName.unset;
  }

  public static final int PARMS_FIELD_NUMBER = 3;
  /**
   * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
   * @return Whether the parms field is set.
   */
  @java.lang.Override
  public boolean hasParms() {
    return msgCase_ == 3;
  }
  /**
   * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
   * @return The parms.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.LbC1.Parms getParms() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.LbC1.Parms) msg_;
    }
    return ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.LbC1.ParmsOrBuilder getParmsOrBuilder() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.LbC1.Parms) msg_;
    }
    return ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (msgCase_ == 2) {
      output.writeEnum(2, ((java.lang.Integer) msg_));
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (ca.wise.fuel.proto.LbC1.Parms) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ((java.lang.Integer) msg_));
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ca.wise.fuel.proto.LbC1.Parms) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.fuel.proto.LbC1)) {
      return super.equals(obj);
    }
    ca.wise.fuel.proto.LbC1 other = (ca.wise.fuel.proto.LbC1) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 2:
        if (getDefaultValue()
            != other.getDefaultValue()) return false;
        break;
      case 3:
        if (!getParms()
            .equals(other.getParms())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    switch (msgCase_) {
      case 2:
        hash = (37 * hash) + DEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + getDefaultValue();
        break;
      case 3:
        hash = (37 * hash) + PARMS_FIELD_NUMBER;
        hash = (53 * hash) + getParms().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.fuel.proto.LbC1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbC1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.LbC1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.LbC1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.fuel.proto.LbC1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.FuelProto.LbC1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.FuelProto.LbC1)
      ca.wise.fuel.proto.LbC1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.fuel.proto.LbC1.class, ca.wise.fuel.proto.LbC1.Builder.class);
    }

    // Construct using ca.wise.fuel.proto.LbC1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.fuel.proto.Lb.internal_static_WISE_FuelProto_LbC1_descriptor;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.LbC1 getDefaultInstanceForType() {
      return ca.wise.fuel.proto.LbC1.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.fuel.proto.LbC1 build() {
      ca.wise.fuel.proto.LbC1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.LbC1 buildPartial() {
      ca.wise.fuel.proto.LbC1 result = new ca.wise.fuel.proto.LbC1(this);
      result.version_ = version_;
      if (msgCase_ == 2) {
        result.msg_ = msg_;
      }
      if (msgCase_ == 3) {
        if (parmsBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = parmsBuilder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.fuel.proto.LbC1) {
        return mergeFrom((ca.wise.fuel.proto.LbC1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.fuel.proto.LbC1 other) {
      if (other == ca.wise.fuel.proto.LbC1.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      switch (other.getMsgCase()) {
        case DEFAULT: {
          setDefaultValue(other.getDefaultValue());
          break;
        }
        case PARMS: {
          mergeParms(other.getParms());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.fuel.proto.LbC1 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.fuel.proto.LbC1) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @return The enum numeric value on the wire for default.
     */
    @java.lang.Override
    public int getDefaultValue() {
      if (msgCase_ == 2) {
        return ((java.lang.Integer) msg_).intValue();
      }
      return 0;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @param value The enum numeric value on the wire for default to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultValue(int value) {
      msgCase_ = 2;
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @return The default.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.FuelName getDefault() {
      if (msgCase_ == 2) {
        @SuppressWarnings("deprecation")
        ca.wise.fuel.proto.FuelName result = ca.wise.fuel.proto.FuelName.valueOf(
            (java.lang.Integer) msg_);
        return result == null ? ca.wise.fuel.proto.FuelName.UNRECOGNIZED : result;
      }
      return ca.wise.fuel.proto.FuelName.unset;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @param value The default to set.
     * @return This builder for chaining.
     */
    public Builder setDefault(ca.wise.fuel.proto.FuelName value) {
      if (value == null) {
        throw new NullPointerException();
      }
      msgCase_ = 2;
      msg_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.WISE.FuelProto.FuelName default = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefault() {
      if (msgCase_ == 2) {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.LbC1.Parms, ca.wise.fuel.proto.LbC1.Parms.Builder, ca.wise.fuel.proto.LbC1.ParmsOrBuilder> parmsBuilder_;
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     * @return Whether the parms field is set.
     */
    @java.lang.Override
    public boolean hasParms() {
      return msgCase_ == 3;
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     * @return The parms.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.LbC1.Parms getParms() {
      if (parmsBuilder_ == null) {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.LbC1.Parms) msg_;
        }
        return ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return parmsBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     */
    public Builder setParms(ca.wise.fuel.proto.LbC1.Parms value) {
      if (parmsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        parmsBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     */
    public Builder setParms(
        ca.wise.fuel.proto.LbC1.Parms.Builder builderForValue) {
      if (parmsBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        parmsBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     */
    public Builder mergeParms(ca.wise.fuel.proto.LbC1.Parms value) {
      if (parmsBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.LbC1.Parms.newBuilder((ca.wise.fuel.proto.LbC1.Parms) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          parmsBuilder_.mergeFrom(value);
        }
        parmsBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     */
    public Builder clearParms() {
      if (parmsBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        parmsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     */
    public ca.wise.fuel.proto.LbC1.Parms.Builder getParmsBuilder() {
      return getParmsFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.LbC1.ParmsOrBuilder getParmsOrBuilder() {
      if ((msgCase_ == 3) && (parmsBuilder_ != null)) {
        return parmsBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.LbC1.Parms) msg_;
        }
        return ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.LbC1.Parms parms = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.LbC1.Parms, ca.wise.fuel.proto.LbC1.Parms.Builder, ca.wise.fuel.proto.LbC1.ParmsOrBuilder> 
        getParmsFieldBuilder() {
      if (parmsBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = ca.wise.fuel.proto.LbC1.Parms.getDefaultInstance();
        }
        parmsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.LbC1.Parms, ca.wise.fuel.proto.LbC1.Parms.Builder, ca.wise.fuel.proto.LbC1.ParmsOrBuilder>(
                (ca.wise.fuel.proto.LbC1.Parms) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return parmsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.FuelProto.LbC1)
  }

  // @@protoc_insertion_point(class_scope:WISE.FuelProto.LbC1)
  private static final ca.wise.fuel.proto.LbC1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.fuel.proto.LbC1();
  }

  public static ca.wise.fuel.proto.LbC1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LbC1>
      PARSER = new com.google.protobuf.AbstractParser<LbC1>() {
    @java.lang.Override
    public LbC1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LbC1(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LbC1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LbC1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.fuel.proto.LbC1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

