// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sfc.proto

package ca.wise.fuel.proto;

public final class Sfc {
  private Sfc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcC1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcC1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcC1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcC1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcC2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcC2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcC2_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcC2_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcC7_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcC7_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcC7_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcC7_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcD2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcD2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcD2_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcD2_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcM1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcM1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcM1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcM1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcO1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcO1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcO1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcO1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcS1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcS1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SfcS1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SfcS1_Parms_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsfc.proto\022\016WISE.FuelProto\032\nmath.proto\032" +
      "\017fuelNames.proto\"\262\002\n\005SfcC1\022\017\n\007version\030\001 " +
      "\001(\005\022+\n\007default\030\002 \001(\0162\030.WISE.FuelProto.Fu" +
      "elNameH\000\022,\n\005parms\030\003 \001(\0132\033.WISE.FuelProto" +
      ".SfcC1.ParmsH\000\032\265\001\n\005Parms\022\017\n\007version\030\001 \001(" +
      "\005\022\021\n\005notes\030\002 \001(\tB\002\030\001\022\030\n\002p1\030\003 \001(\0132\014.Math." +
      "Double\022\030\n\002p2\030\004 \001(\0132\014.Math.Double\022\030\n\002p3\030\005" +
      " \001(\0132\014.Math.Double\022\030\n\002p4\030\006 \001(\0132\014.Math.Do" +
      "uble\022 \n\nmultiplier\030\007 \001(\0132\014.Math.DoubleB\005" +
      "\n\003msg\"\233\002\n\005SfcC2\022\017\n\007version\030\001 \001(\005\022+\n\007defa" +
      "ult\030\002 \001(\0162\030.WISE.FuelProto.FuelNameH\000\022,\n" +
      "\005parms\030\003 \001(\0132\033.WISE.FuelProto.SfcC2.Parm" +
      "sH\000\032\236\001\n\005Parms\022\017\n\007version\030\001 \001(\005\022\021\n\005notes\030" +
      "\002 \001(\tB\002\030\001\022\030\n\002p1\030\003 \001(\0132\014.Math.Double\022\030\n\002p" +
      "2\030\004 \001(\0132\014.Math.Double\022\033\n\005power\030\005 \001(\0132\014.M" +
      "ath.Double\022 \n\nmultiplier\030\006 \001(\0132\014.Math.Do" +
      "ubleB\005\n\003msg\"\213\003\n\005SfcC7\022\017\n\007version\030\001 \001(\005\022+" +
      "\n\007default\030\002 \001(\0162\030.WISE.FuelProto.FuelNam" +
      "eH\000\022,\n\005parms\030\003 \001(\0132\033.WISE.FuelProto.SfcC" +
      "7.ParmsH\000\032\216\002\n\005Parms\022\017\n\007version\030\001 \001(\005\022\031\n\003" +
      "p1F\030\002 \001(\0132\014.Math.Double\022\031\n\003p2F\030\003 \001(\0132\014.M" +
      "ath.Double\022\031\n\003p3F\030\004 \001(\0132\014.Math.Double\022\031\n" +
      "\003p1W\030\005 \001(\0132\014.Math.Double\022\031\n\003p2W\030\006 \001(\0132\014." +
      "Math.Double\022#\n\rffcMultiplier\030\007 \001(\0132\014.Mat" +
      "h.Double\022#\n\rwfcMultiplier\030\010 \001(\0132\014.Math.D" +
      "ouble\022#\n\rsfcMultiplier\030\t \001(\0132\014.Math.Doub" +
      "leB\005\n\003msg\"\370\002\n\005SfcD2\022\017\n\007version\030\001 \001(\005\022+\n\007" +
      "default\030\002 \001(\0162\030.WISE.FuelProto.FuelNameH" +
      "\000\022,\n\005parms\030\003 \001(\0132\033.WISE.FuelProto.SfcD2." +
      "ParmsH\000\032\373\001\n\005Parms\022\017\n\007version\030\001 \001(\005\022\021\n\005no" +
      "tes\030\002 \001(\tB\002\030\001\022\030\n\002p1\030\003 \001(\0132\014.Math.Double\022" +
      "\030\n\002p2\030\004 \001(\0132\014.Math.Double\022\033\n\005power\030\005 \001(\013" +
      "2\014.Math.Double\022 \n\nmultiplier\030\006 \001(\0132\014.Mat" +
      "h.Double\022\037\n\tthreshold\030\007 \001(\0132\014.Math.Doubl" +
      "e\022\034\n\006scale1\030\010 \001(\0132\014.Math.Double\022\034\n\006scale" +
      "2\030\t \001(\0132\014.Math.DoubleB\005\n\003msg\"\224\001\n\005SfcM1\022\017" +
      "\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030.WISE." +
      "FuelProto.FuelNameH\000\022,\n\005parms\030\003 \001(\0132\033.WI" +
      "SE.FuelProto.SfcM1.ParmsH\000\032\030\n\005Parms\022\017\n\007v" +
      "ersion\030\001 \001(\005B\005\n\003msg\"\307\001\n\005SfcO1\022\017\n\007version" +
      "\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030.WISE.FuelProto" +
      ".FuelNameH\000\022,\n\005parms\030\003 \001(\0132\033.WISE.FuelPr" +
      "oto.SfcO1.ParmsH\000\032K\n\005Parms\022\017\n\007version\030\001 " +
      "\001(\005\022\036\n\010fuelLoad\030\002 \001(\0132\014.Math.Double\022\021\n\005n" +
      "otes\030\003 \001(\tB\002\030\001B\005\n\003msg\"\300\003\n\005SfcS1\022\017\n\007versi" +
      "on\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030.WISE.FuelPro" +
      "to.FuelNameH\000\022,\n\005parms\030\003 \001(\0132\033.WISE.Fuel" +
      "Proto.SfcS1.ParmsH\000\032\303\002\n\005Parms\022\017\n\007version" +
      "\030\001 \001(\005\022\031\n\003p1F\030\002 \001(\0132\014.Math.Double\022\031\n\003p2F" +
      "\030\003 \001(\0132\014.Math.Double\022\031\n\003p1W\030\004 \001(\0132\014.Math" +
      ".Double\022\031\n\003p2W\030\005 \001(\0132\014.Math.Double\022#\n\rff" +
      "cMultiplier\030\006 \001(\0132\014.Math.Double\022#\n\rwfcMu" +
      "ltiplier\030\007 \001(\0132\014.Math.Double\022#\n\rsfcMulti" +
      "plier\030\010 \001(\0132\014.Math.Double\022&\n\020ffcBuiMulti" +
      "plier\030\t \001(\0132\014.Math.Double\022&\n\020wfcBuiMulti" +
      "plier\030\n \001(\0132\014.Math.DoubleB\005\n\003msgB\'\n\022ca.w" +
      "ise.fuel.protoP\001\252\002\016WISE.FuelProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          ca.wise.fuel.proto.FuelNames.getDescriptor(),
        });
    internal_static_WISE_FuelProto_SfcC1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_FuelProto_SfcC1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcC1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SfcC1_Parms_descriptor =
      internal_static_WISE_FuelProto_SfcC1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SfcC1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcC1_Parms_descriptor,
        new java.lang.String[] { "Version", "Notes", "P1", "P2", "P3", "P4", "Multiplier", });
    internal_static_WISE_FuelProto_SfcC2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WISE_FuelProto_SfcC2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcC2_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SfcC2_Parms_descriptor =
      internal_static_WISE_FuelProto_SfcC2_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SfcC2_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcC2_Parms_descriptor,
        new java.lang.String[] { "Version", "Notes", "P1", "P2", "Power", "Multiplier", });
    internal_static_WISE_FuelProto_SfcC7_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WISE_FuelProto_SfcC7_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcC7_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SfcC7_Parms_descriptor =
      internal_static_WISE_FuelProto_SfcC7_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SfcC7_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcC7_Parms_descriptor,
        new java.lang.String[] { "Version", "P1F", "P2F", "P3F", "P1W", "P2W", "FfcMultiplier", "WfcMultiplier", "SfcMultiplier", });
    internal_static_WISE_FuelProto_SfcD2_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WISE_FuelProto_SfcD2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcD2_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SfcD2_Parms_descriptor =
      internal_static_WISE_FuelProto_SfcD2_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SfcD2_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcD2_Parms_descriptor,
        new java.lang.String[] { "Version", "Notes", "P1", "P2", "Power", "Multiplier", "Threshold", "Scale1", "Scale2", });
    internal_static_WISE_FuelProto_SfcM1_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_WISE_FuelProto_SfcM1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcM1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SfcM1_Parms_descriptor =
      internal_static_WISE_FuelProto_SfcM1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SfcM1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcM1_Parms_descriptor,
        new java.lang.String[] { "Version", });
    internal_static_WISE_FuelProto_SfcO1_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_WISE_FuelProto_SfcO1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcO1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SfcO1_Parms_descriptor =
      internal_static_WISE_FuelProto_SfcO1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SfcO1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcO1_Parms_descriptor,
        new java.lang.String[] { "Version", "FuelLoad", "Notes", });
    internal_static_WISE_FuelProto_SfcS1_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_WISE_FuelProto_SfcS1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcS1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SfcS1_Parms_descriptor =
      internal_static_WISE_FuelProto_SfcS1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SfcS1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SfcS1_Parms_descriptor,
        new java.lang.String[] { "Version", "P1F", "P2F", "P1W", "P2W", "FfcMultiplier", "WfcMultiplier", "SfcMultiplier", "FfcBuiMultiplier", "WfcBuiMultiplier", });
    ca.hss.math.proto.Math.getDescriptor();
    ca.wise.fuel.proto.FuelNames.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
