// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spreadParms.proto

package ca.wise.fuel.proto;

public final class SpreadParms {
  private SpreadParms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsS1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsS1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsS1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsS1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsC1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsC1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsC1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsC1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsC6_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsC6_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsC6_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsC6_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsD1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsD1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsD1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsD1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsNz_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsNz_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsNz_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsNz_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsO1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsO1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsO1_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsO1_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsO1ab_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsO1ab_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsO1ab_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsO1ab_Parms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsNon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsNon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_FuelProto_SpreadParmsNon_Parms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_FuelProto_SpreadParmsNon_Parms_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021spreadParms.proto\022\016WISE.FuelProto\032\nmat" +
      "h.proto\032\017fuelNames.proto\"\302\002\n\rSpreadParms" +
      "S1\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030.W" +
      "ISE.FuelProto.FuelNameH\000\0224\n\005parms\030\003 \001(\0132" +
      "#.WISE.FuelProto.SpreadParmsS1.ParmsH\000\032\265" +
      "\001\n\005Parms\022\017\n\007version\030\001 \001(\005\022\027\n\001a\030\002 \001(\0132\014.M" +
      "ath.Double\022\027\n\001b\030\003 \001(\0132\014.Math.Double\022\027\n\001c" +
      "\030\004 \001(\0132\014.Math.Double\022\027\n\001q\030\005 \001(\0132\014.Math.D" +
      "ouble\022\032\n\004bui0\030\006 \001(\0132\014.Math.Double\022\033\n\005max" +
      "Be\030\007 \001(\0132\014.Math.DoubleB\005\n\003msg\"\226\003\n\rSpread" +
      "ParmsC1\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(" +
      "\0162\030.WISE.FuelProto.FuelNameH\000\0224\n\005parms\030\003" +
      " \001(\0132#.WISE.FuelProto.SpreadParmsC1.Parm" +
      "sH\000\032\211\002\n\005Parms\022\017\n\007version\030\001 \001(\005\022\027\n\001a\030\002 \001(" +
      "\0132\014.Math.Double\022\027\n\001b\030\003 \001(\0132\014.Math.Double" +
      "\022\027\n\001c\030\004 \001(\0132\014.Math.Double\022\027\n\001q\030\005 \001(\0132\014.M" +
      "ath.Double\022\032\n\004bui0\030\006 \001(\0132\014.Math.Double\022\033" +
      "\n\005maxBe\030\007 \001(\0132\014.Math.Double\022\034\n\006height\030\010 " +
      "\001(\0132\014.Math.Double\022\031\n\003cbh\030\t \001(\0132\014.Math.Do" +
      "uble\022\031\n\003cfl\030\n \001(\0132\014.Math.DoubleB\005\n\003msg\"\226" +
      "\003\n\rSpreadParmsC6\022\017\n\007version\030\001 \001(\005\022+\n\007def" +
      "ault\030\002 \001(\0162\030.WISE.FuelProto.FuelNameH\000\0224" +
      "\n\005parms\030\003 \001(\0132#.WISE.FuelProto.SpreadPar" +
      "msC6.ParmsH\000\032\211\002\n\005Parms\022\017\n\007version\030\001 \001(\005\022" +
      "\027\n\001a\030\002 \001(\0132\014.Math.Double\022\027\n\001b\030\003 \001(\0132\014.Ma" +
      "th.Double\022\027\n\001c\030\004 \001(\0132\014.Math.Double\022\027\n\001q\030" +
      "\005 \001(\0132\014.Math.Double\022\032\n\004bui0\030\006 \001(\0132\014.Math" +
      ".Double\022\033\n\005maxBe\030\007 \001(\0132\014.Math.Double\022\034\n\006" +
      "height\030\010 \001(\0132\014.Math.Double\022\031\n\003cbh\030\t \001(\0132" +
      "\014.Math.Double\022\031\n\003cfl\030\n \001(\0132\014.Math.Double" +
      "B\005\n\003msg\"\226\003\n\rSpreadParmsD1\022\017\n\007version\030\001 \001" +
      "(\005\022+\n\007default\030\002 \001(\0162\030.WISE.FuelProto.Fue" +
      "lNameH\000\0224\n\005parms\030\003 \001(\0132#.WISE.FuelProto." +
      "SpreadParmsD1.ParmsH\000\032\211\002\n\005Parms\022\017\n\007versi" +
      "on\030\001 \001(\005\022\027\n\001a\030\002 \001(\0132\014.Math.Double\022\027\n\001b\030\003" +
      " \001(\0132\014.Math.Double\022\027\n\001c\030\004 \001(\0132\014.Math.Dou" +
      "ble\022\027\n\001q\030\005 \001(\0132\014.Math.Double\022\032\n\004bui0\030\006 \001" +
      "(\0132\014.Math.Double\022\033\n\005maxBe\030\007 \001(\0132\014.Math.D" +
      "ouble\022\034\n\006height\030\010 \001(\0132\014.Math.Double\022\031\n\003c" +
      "bh\030\t \001(\0132\014.Math.Double\022\031\n\003cfl\030\n \001(\0132\014.Ma" +
      "th.DoubleB\005\n\003msg\"\226\003\n\rSpreadParmsNz\022\017\n\007ve" +
      "rsion\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030.WISE.Fuel" +
      "Proto.FuelNameH\000\0224\n\005parms\030\003 \001(\0132#.WISE.F" +
      "uelProto.SpreadParmsNz.ParmsH\000\032\211\002\n\005Parms" +
      "\022\017\n\007version\030\001 \001(\005\022\027\n\001a\030\002 \001(\0132\014.Math.Doub" +
      "le\022\027\n\001b\030\003 \001(\0132\014.Math.Double\022\027\n\001c\030\004 \001(\0132\014" +
      ".Math.Double\022\027\n\001q\030\005 \001(\0132\014.Math.Double\022\032\n" +
      "\004bui0\030\006 \001(\0132\014.Math.Double\022\033\n\005maxBe\030\007 \001(\013" +
      "2\014.Math.Double\022\034\n\006height\030\010 \001(\0132\014.Math.Do" +
      "uble\022\031\n\003cbh\030\t \001(\0132\014.Math.Double\022\031\n\003cfl\030\n" +
      " \001(\0132\014.Math.DoubleB\005\n\003msg\"\346\002\n\rSpreadParm" +
      "sO1\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030." +
      "WISE.FuelProto.FuelNameH\000\0224\n\005parms\030\003 \001(\013" +
      "2#.WISE.FuelProto.SpreadParmsO1.ParmsH\000\032" +
      "\331\001\n\005Parms\022\017\n\007version\030\001 \001(\005\022\027\n\001a\030\002 \001(\0132\014." +
      "Math.Double\022\027\n\001b\030\003 \001(\0132\014.Math.Double\022\027\n\001" +
      "c\030\004 \001(\0132\014.Math.Double\022\027\n\001q\030\005 \001(\0132\014.Math." +
      "Double\022\032\n\004bui0\030\006 \001(\0132\014.Math.Double\022\033\n\005ma" +
      "xBe\030\007 \001(\0132\014.Math.Double\022\"\n\014curingDegree\030" +
      "\010 \001(\0132\014.Math.DoubleB\005\n\003msg\"\331\003\n\017SpreadPar" +
      "msO1ab\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\016" +
      "2\030.WISE.FuelProto.FuelNameH\000\0226\n\005parms\030\003 " +
      "\001(\0132%.WISE.FuelProto.SpreadParmsO1ab.Par" +
      "msH\000\032\310\002\n\005Parms\022\017\n\007version\030\001 \001(\005\022\027\n\001a\030\002 \001" +
      "(\0132\014.Math.Double\022\027\n\001b\030\003 \001(\0132\014.Math.Doubl" +
      "e\022\027\n\001c\030\004 \001(\0132\014.Math.Double\022\027\n\001q\030\005 \001(\0132\014." +
      "Math.Double\022\032\n\004bui0\030\006 \001(\0132\014.Math.Double\022" +
      "\033\n\005maxBe\030\007 \001(\0132\014.Math.Double\022\"\n\014curingDe" +
      "gree\030\010 \001(\0132\014.Math.Double\022#\n\ro1AbStanding" +
      "A\030\t \001(\0132\014.Math.Double\022#\n\ro1AbStandingB\030\n" +
      " \001(\0132\014.Math.Double\022#\n\ro1AbStandingC\030\013 \001(" +
      "\0132\014.Math.DoubleB\005\n\003msg\"\246\001\n\016SpreadParmsNo" +
      "n\022\017\n\007version\030\001 \001(\005\022+\n\007default\030\002 \001(\0162\030.WI" +
      "SE.FuelProto.FuelNameH\000\0225\n\005parms\030\003 \001(\0132$" +
      ".WISE.FuelProto.SpreadParmsNon.ParmsH\000\032\030" +
      "\n\005Parms\022\017\n\007version\030\001 \001(\005B\005\n\003msgB\'\n\022ca.wi" +
      "se.fuel.protoP\001\252\002\016WISE.FuelProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.hss.math.proto.Math.getDescriptor(),
          ca.wise.fuel.proto.FuelNames.getDescriptor(),
        });
    internal_static_WISE_FuelProto_SpreadParmsS1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsS1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsS1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsS1_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsS1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsS1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsS1_Parms_descriptor,
        new java.lang.String[] { "Version", "A", "B", "C", "Q", "Bui0", "MaxBe", });
    internal_static_WISE_FuelProto_SpreadParmsC1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WISE_FuelProto_SpreadParmsC1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsC1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsC1_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsC1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsC1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsC1_Parms_descriptor,
        new java.lang.String[] { "Version", "A", "B", "C", "Q", "Bui0", "MaxBe", "Height", "Cbh", "Cfl", });
    internal_static_WISE_FuelProto_SpreadParmsC6_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WISE_FuelProto_SpreadParmsC6_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsC6_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsC6_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsC6_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsC6_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsC6_Parms_descriptor,
        new java.lang.String[] { "Version", "A", "B", "C", "Q", "Bui0", "MaxBe", "Height", "Cbh", "Cfl", });
    internal_static_WISE_FuelProto_SpreadParmsD1_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WISE_FuelProto_SpreadParmsD1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsD1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsD1_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsD1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsD1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsD1_Parms_descriptor,
        new java.lang.String[] { "Version", "A", "B", "C", "Q", "Bui0", "MaxBe", "Height", "Cbh", "Cfl", });
    internal_static_WISE_FuelProto_SpreadParmsNz_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_WISE_FuelProto_SpreadParmsNz_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsNz_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsNz_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsNz_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsNz_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsNz_Parms_descriptor,
        new java.lang.String[] { "Version", "A", "B", "C", "Q", "Bui0", "MaxBe", "Height", "Cbh", "Cfl", });
    internal_static_WISE_FuelProto_SpreadParmsO1_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_WISE_FuelProto_SpreadParmsO1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsO1_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsO1_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsO1_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsO1_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsO1_Parms_descriptor,
        new java.lang.String[] { "Version", "A", "B", "C", "Q", "Bui0", "MaxBe", "CuringDegree", });
    internal_static_WISE_FuelProto_SpreadParmsO1ab_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_WISE_FuelProto_SpreadParmsO1ab_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsO1ab_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsO1ab_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsO1ab_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsO1ab_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsO1ab_Parms_descriptor,
        new java.lang.String[] { "Version", "A", "B", "C", "Q", "Bui0", "MaxBe", "CuringDegree", "O1AbStandingA", "O1AbStandingB", "O1AbStandingC", });
    internal_static_WISE_FuelProto_SpreadParmsNon_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_WISE_FuelProto_SpreadParmsNon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsNon_descriptor,
        new java.lang.String[] { "Version", "Default", "Parms", "Msg", });
    internal_static_WISE_FuelProto_SpreadParmsNon_Parms_descriptor =
      internal_static_WISE_FuelProto_SpreadParmsNon_descriptor.getNestedTypes().get(0);
    internal_static_WISE_FuelProto_SpreadParmsNon_Parms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_FuelProto_SpreadParmsNon_Parms_descriptor,
        new java.lang.String[] { "Version", });
    ca.hss.math.proto.Math.getDescriptor();
    ca.wise.fuel.proto.FuelNames.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
