// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccwfgmFuel.proto

package ca.wise.fuel.proto;

/**
 * Protobuf type {@code WISE.FuelProto.SpreadParmsAttribute}
 */
public final class SpreadParmsAttribute extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.FuelProto.SpreadParmsAttribute)
    SpreadParmsAttributeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpreadParmsAttribute.newBuilder() to construct.
  private SpreadParmsAttribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpreadParmsAttribute() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpreadParmsAttribute();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpreadParmsAttribute(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            commonField_ = input.readInt64();
            break;
          }
          case 26: {
            ca.wise.fuel.proto.SpreadParmsS1.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsS1) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsS1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsS1) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          case 34: {
            ca.wise.fuel.proto.SpreadParmsC1.Builder subBuilder = null;
            if (msgCase_ == 4) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsC1) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsC1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsC1) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 4;
            break;
          }
          case 42: {
            ca.wise.fuel.proto.SpreadParmsC6.Builder subBuilder = null;
            if (msgCase_ == 5) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsC6) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsC6.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsC6) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 5;
            break;
          }
          case 50: {
            ca.wise.fuel.proto.SpreadParmsD1.Builder subBuilder = null;
            if (msgCase_ == 6) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsD1) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsD1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsD1) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 6;
            break;
          }
          case 58: {
            ca.wise.fuel.proto.SpreadParmsNz.Builder subBuilder = null;
            if (msgCase_ == 7) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsNz) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsNz.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsNz) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 7;
            break;
          }
          case 66: {
            ca.wise.fuel.proto.SpreadParmsO1.Builder subBuilder = null;
            if (msgCase_ == 8) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsO1) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsO1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsO1) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 8;
            break;
          }
          case 74: {
            ca.wise.fuel.proto.SpreadParmsO1ab.Builder subBuilder = null;
            if (msgCase_ == 9) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsO1ab) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsO1ab.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsO1ab) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 9;
            break;
          }
          case 82: {
            ca.wise.fuel.proto.SpreadParmsMixed.Builder subBuilder = null;
            if (msgCase_ == 10) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsMixed) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsMixed.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsMixed) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 10;
            break;
          }
          case 90: {
            ca.wise.fuel.proto.SpreadParmsMixedDead.Builder subBuilder = null;
            if (msgCase_ == 11) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsMixedDead) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsMixedDead.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsMixedDead) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 11;
            break;
          }
          case 98: {
            ca.wise.fuel.proto.SpreadParmsNon.Builder subBuilder = null;
            if (msgCase_ == 12) {
              subBuilder = ((ca.wise.fuel.proto.SpreadParmsNon) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(ca.wise.fuel.proto.SpreadParmsNon.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.fuel.proto.SpreadParmsNon) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 12;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_SpreadParmsAttribute_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_SpreadParmsAttribute_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.fuel.proto.SpreadParmsAttribute.class, ca.wise.fuel.proto.SpreadParmsAttribute.Builder.class);
  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    S1(3),
    C1(4),
    C6(5),
    D1(6),
    NZ(7),
    O1(8),
    O1AB(9),
    MIXED(10),
    MIXEDDEAD(11),
    NON(12),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 3: return S1;
        case 4: return C1;
        case 5: return C6;
        case 6: return D1;
        case 7: return NZ;
        case 8: return O1;
        case 9: return O1AB;
        case 10: return MIXED;
        case 11: return MIXEDDEAD;
        case 12: return NON;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int COMMONFIELD_FIELD_NUMBER = 2;
  private long commonField_;
  /**
   * <code>int64 commonField = 2 [deprecated = true];</code>
   * @return The commonField.
   */
  @java.lang.Override
  @java.lang.Deprecated public long getCommonField() {
    return commonField_;
  }

  public static final int S1_FIELD_NUMBER = 3;
  /**
   * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
   * @return Whether the s1 field is set.
   */
  @java.lang.Override
  public boolean hasS1() {
    return msgCase_ == 3;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
   * @return The s1.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsS1 getS1() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.SpreadParmsS1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsS1.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsS1OrBuilder getS1OrBuilder() {
    if (msgCase_ == 3) {
       return (ca.wise.fuel.proto.SpreadParmsS1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsS1.getDefaultInstance();
  }

  public static final int C1_FIELD_NUMBER = 4;
  /**
   * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
   * @return Whether the c1 field is set.
   */
  @java.lang.Override
  public boolean hasC1() {
    return msgCase_ == 4;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
   * @return The c1.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsC1 getC1() {
    if (msgCase_ == 4) {
       return (ca.wise.fuel.proto.SpreadParmsC1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsC1.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsC1OrBuilder getC1OrBuilder() {
    if (msgCase_ == 4) {
       return (ca.wise.fuel.proto.SpreadParmsC1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsC1.getDefaultInstance();
  }

  public static final int C6_FIELD_NUMBER = 5;
  /**
   * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
   * @return Whether the c6 field is set.
   */
  @java.lang.Override
  public boolean hasC6() {
    return msgCase_ == 5;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
   * @return The c6.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsC6 getC6() {
    if (msgCase_ == 5) {
       return (ca.wise.fuel.proto.SpreadParmsC6) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsC6.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsC6OrBuilder getC6OrBuilder() {
    if (msgCase_ == 5) {
       return (ca.wise.fuel.proto.SpreadParmsC6) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsC6.getDefaultInstance();
  }

  public static final int D1_FIELD_NUMBER = 6;
  /**
   * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
   * @return Whether the d1 field is set.
   */
  @java.lang.Override
  public boolean hasD1() {
    return msgCase_ == 6;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
   * @return The d1.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsD1 getD1() {
    if (msgCase_ == 6) {
       return (ca.wise.fuel.proto.SpreadParmsD1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsD1.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsD1OrBuilder getD1OrBuilder() {
    if (msgCase_ == 6) {
       return (ca.wise.fuel.proto.SpreadParmsD1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsD1.getDefaultInstance();
  }

  public static final int NZ_FIELD_NUMBER = 7;
  /**
   * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
   * @return Whether the nz field is set.
   */
  @java.lang.Override
  public boolean hasNz() {
    return msgCase_ == 7;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
   * @return The nz.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsNz getNz() {
    if (msgCase_ == 7) {
       return (ca.wise.fuel.proto.SpreadParmsNz) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsNz.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsNzOrBuilder getNzOrBuilder() {
    if (msgCase_ == 7) {
       return (ca.wise.fuel.proto.SpreadParmsNz) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsNz.getDefaultInstance();
  }

  public static final int O1_FIELD_NUMBER = 8;
  /**
   * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
   * @return Whether the o1 field is set.
   */
  @java.lang.Override
  public boolean hasO1() {
    return msgCase_ == 8;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
   * @return The o1.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsO1 getO1() {
    if (msgCase_ == 8) {
       return (ca.wise.fuel.proto.SpreadParmsO1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsO1.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsO1OrBuilder getO1OrBuilder() {
    if (msgCase_ == 8) {
       return (ca.wise.fuel.proto.SpreadParmsO1) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsO1.getDefaultInstance();
  }

  public static final int O1AB_FIELD_NUMBER = 9;
  /**
   * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
   * @return Whether the o1ab field is set.
   */
  @java.lang.Override
  public boolean hasO1Ab() {
    return msgCase_ == 9;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
   * @return The o1ab.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsO1ab getO1Ab() {
    if (msgCase_ == 9) {
       return (ca.wise.fuel.proto.SpreadParmsO1ab) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsO1ab.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsO1abOrBuilder getO1AbOrBuilder() {
    if (msgCase_ == 9) {
       return (ca.wise.fuel.proto.SpreadParmsO1ab) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsO1ab.getDefaultInstance();
  }

  public static final int MIXED_FIELD_NUMBER = 10;
  /**
   * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
   * @return Whether the mixed field is set.
   */
  @java.lang.Override
  public boolean hasMixed() {
    return msgCase_ == 10;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
   * @return The mixed.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsMixed getMixed() {
    if (msgCase_ == 10) {
       return (ca.wise.fuel.proto.SpreadParmsMixed) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsMixed.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsMixedOrBuilder getMixedOrBuilder() {
    if (msgCase_ == 10) {
       return (ca.wise.fuel.proto.SpreadParmsMixed) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsMixed.getDefaultInstance();
  }

  public static final int MIXEDDEAD_FIELD_NUMBER = 11;
  /**
   * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
   * @return Whether the mixedDead field is set.
   */
  @java.lang.Override
  public boolean hasMixedDead() {
    return msgCase_ == 11;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
   * @return The mixedDead.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsMixedDead getMixedDead() {
    if (msgCase_ == 11) {
       return (ca.wise.fuel.proto.SpreadParmsMixedDead) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsMixedDead.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsMixedDeadOrBuilder getMixedDeadOrBuilder() {
    if (msgCase_ == 11) {
       return (ca.wise.fuel.proto.SpreadParmsMixedDead) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsMixedDead.getDefaultInstance();
  }

  public static final int NON_FIELD_NUMBER = 12;
  /**
   * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
   * @return Whether the non field is set.
   */
  @java.lang.Override
  public boolean hasNon() {
    return msgCase_ == 12;
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
   * @return The non.
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsNon getNon() {
    if (msgCase_ == 12) {
       return (ca.wise.fuel.proto.SpreadParmsNon) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsNon.getDefaultInstance();
  }
  /**
   * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
   */
  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsNonOrBuilder getNonOrBuilder() {
    if (msgCase_ == 12) {
       return (ca.wise.fuel.proto.SpreadParmsNon) msg_;
    }
    return ca.wise.fuel.proto.SpreadParmsNon.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (commonField_ != 0L) {
      output.writeInt64(2, commonField_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (ca.wise.fuel.proto.SpreadParmsS1) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (ca.wise.fuel.proto.SpreadParmsC1) msg_);
    }
    if (msgCase_ == 5) {
      output.writeMessage(5, (ca.wise.fuel.proto.SpreadParmsC6) msg_);
    }
    if (msgCase_ == 6) {
      output.writeMessage(6, (ca.wise.fuel.proto.SpreadParmsD1) msg_);
    }
    if (msgCase_ == 7) {
      output.writeMessage(7, (ca.wise.fuel.proto.SpreadParmsNz) msg_);
    }
    if (msgCase_ == 8) {
      output.writeMessage(8, (ca.wise.fuel.proto.SpreadParmsO1) msg_);
    }
    if (msgCase_ == 9) {
      output.writeMessage(9, (ca.wise.fuel.proto.SpreadParmsO1ab) msg_);
    }
    if (msgCase_ == 10) {
      output.writeMessage(10, (ca.wise.fuel.proto.SpreadParmsMixed) msg_);
    }
    if (msgCase_ == 11) {
      output.writeMessage(11, (ca.wise.fuel.proto.SpreadParmsMixedDead) msg_);
    }
    if (msgCase_ == 12) {
      output.writeMessage(12, (ca.wise.fuel.proto.SpreadParmsNon) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (commonField_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, commonField_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ca.wise.fuel.proto.SpreadParmsS1) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ca.wise.fuel.proto.SpreadParmsC1) msg_);
    }
    if (msgCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (ca.wise.fuel.proto.SpreadParmsC6) msg_);
    }
    if (msgCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (ca.wise.fuel.proto.SpreadParmsD1) msg_);
    }
    if (msgCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (ca.wise.fuel.proto.SpreadParmsNz) msg_);
    }
    if (msgCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (ca.wise.fuel.proto.SpreadParmsO1) msg_);
    }
    if (msgCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (ca.wise.fuel.proto.SpreadParmsO1ab) msg_);
    }
    if (msgCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (ca.wise.fuel.proto.SpreadParmsMixed) msg_);
    }
    if (msgCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (ca.wise.fuel.proto.SpreadParmsMixedDead) msg_);
    }
    if (msgCase_ == 12) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, (ca.wise.fuel.proto.SpreadParmsNon) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.fuel.proto.SpreadParmsAttribute)) {
      return super.equals(obj);
    }
    ca.wise.fuel.proto.SpreadParmsAttribute other = (ca.wise.fuel.proto.SpreadParmsAttribute) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (getCommonField()
        != other.getCommonField()) return false;
    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 3:
        if (!getS1()
            .equals(other.getS1())) return false;
        break;
      case 4:
        if (!getC1()
            .equals(other.getC1())) return false;
        break;
      case 5:
        if (!getC6()
            .equals(other.getC6())) return false;
        break;
      case 6:
        if (!getD1()
            .equals(other.getD1())) return false;
        break;
      case 7:
        if (!getNz()
            .equals(other.getNz())) return false;
        break;
      case 8:
        if (!getO1()
            .equals(other.getO1())) return false;
        break;
      case 9:
        if (!getO1Ab()
            .equals(other.getO1Ab())) return false;
        break;
      case 10:
        if (!getMixed()
            .equals(other.getMixed())) return false;
        break;
      case 11:
        if (!getMixedDead()
            .equals(other.getMixedDead())) return false;
        break;
      case 12:
        if (!getNon()
            .equals(other.getNon())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + COMMONFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommonField());
    switch (msgCase_) {
      case 3:
        hash = (37 * hash) + S1_FIELD_NUMBER;
        hash = (53 * hash) + getS1().hashCode();
        break;
      case 4:
        hash = (37 * hash) + C1_FIELD_NUMBER;
        hash = (53 * hash) + getC1().hashCode();
        break;
      case 5:
        hash = (37 * hash) + C6_FIELD_NUMBER;
        hash = (53 * hash) + getC6().hashCode();
        break;
      case 6:
        hash = (37 * hash) + D1_FIELD_NUMBER;
        hash = (53 * hash) + getD1().hashCode();
        break;
      case 7:
        hash = (37 * hash) + NZ_FIELD_NUMBER;
        hash = (53 * hash) + getNz().hashCode();
        break;
      case 8:
        hash = (37 * hash) + O1_FIELD_NUMBER;
        hash = (53 * hash) + getO1().hashCode();
        break;
      case 9:
        hash = (37 * hash) + O1AB_FIELD_NUMBER;
        hash = (53 * hash) + getO1Ab().hashCode();
        break;
      case 10:
        hash = (37 * hash) + MIXED_FIELD_NUMBER;
        hash = (53 * hash) + getMixed().hashCode();
        break;
      case 11:
        hash = (37 * hash) + MIXEDDEAD_FIELD_NUMBER;
        hash = (53 * hash) + getMixedDead().hashCode();
        break;
      case 12:
        hash = (37 * hash) + NON_FIELD_NUMBER;
        hash = (53 * hash) + getNon().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.fuel.proto.SpreadParmsAttribute parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.fuel.proto.SpreadParmsAttribute prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.FuelProto.SpreadParmsAttribute}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.FuelProto.SpreadParmsAttribute)
      ca.wise.fuel.proto.SpreadParmsAttributeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_SpreadParmsAttribute_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_SpreadParmsAttribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.fuel.proto.SpreadParmsAttribute.class, ca.wise.fuel.proto.SpreadParmsAttribute.Builder.class);
    }

    // Construct using ca.wise.fuel.proto.SpreadParmsAttribute.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      commonField_ = 0L;

      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.fuel.proto.CcwfgmFuelOuterClass.internal_static_WISE_FuelProto_SpreadParmsAttribute_descriptor;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsAttribute getDefaultInstanceForType() {
      return ca.wise.fuel.proto.SpreadParmsAttribute.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsAttribute build() {
      ca.wise.fuel.proto.SpreadParmsAttribute result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsAttribute buildPartial() {
      ca.wise.fuel.proto.SpreadParmsAttribute result = new ca.wise.fuel.proto.SpreadParmsAttribute(this);
      result.version_ = version_;
      result.commonField_ = commonField_;
      if (msgCase_ == 3) {
        if (s1Builder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = s1Builder_.build();
        }
      }
      if (msgCase_ == 4) {
        if (c1Builder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = c1Builder_.build();
        }
      }
      if (msgCase_ == 5) {
        if (c6Builder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = c6Builder_.build();
        }
      }
      if (msgCase_ == 6) {
        if (d1Builder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = d1Builder_.build();
        }
      }
      if (msgCase_ == 7) {
        if (nzBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = nzBuilder_.build();
        }
      }
      if (msgCase_ == 8) {
        if (o1Builder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = o1Builder_.build();
        }
      }
      if (msgCase_ == 9) {
        if (o1AbBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = o1AbBuilder_.build();
        }
      }
      if (msgCase_ == 10) {
        if (mixedBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = mixedBuilder_.build();
        }
      }
      if (msgCase_ == 11) {
        if (mixedDeadBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = mixedDeadBuilder_.build();
        }
      }
      if (msgCase_ == 12) {
        if (nonBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = nonBuilder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.fuel.proto.SpreadParmsAttribute) {
        return mergeFrom((ca.wise.fuel.proto.SpreadParmsAttribute)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.fuel.proto.SpreadParmsAttribute other) {
      if (other == ca.wise.fuel.proto.SpreadParmsAttribute.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getCommonField() != 0L) {
        setCommonField(other.getCommonField());
      }
      switch (other.getMsgCase()) {
        case S1: {
          mergeS1(other.getS1());
          break;
        }
        case C1: {
          mergeC1(other.getC1());
          break;
        }
        case C6: {
          mergeC6(other.getC6());
          break;
        }
        case D1: {
          mergeD1(other.getD1());
          break;
        }
        case NZ: {
          mergeNz(other.getNz());
          break;
        }
        case O1: {
          mergeO1(other.getO1());
          break;
        }
        case O1AB: {
          mergeO1Ab(other.getO1Ab());
          break;
        }
        case MIXED: {
          mergeMixed(other.getMixed());
          break;
        }
        case MIXEDDEAD: {
          mergeMixedDead(other.getMixedDead());
          break;
        }
        case NON: {
          mergeNon(other.getNon());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.fuel.proto.SpreadParmsAttribute parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.fuel.proto.SpreadParmsAttribute) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private long commonField_ ;
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @return The commonField.
     */
    @java.lang.Override
    @java.lang.Deprecated public long getCommonField() {
      return commonField_;
    }
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @param value The commonField to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setCommonField(long value) {
      
      commonField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 commonField = 2 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearCommonField() {
      
      commonField_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsS1, ca.wise.fuel.proto.SpreadParmsS1.Builder, ca.wise.fuel.proto.SpreadParmsS1OrBuilder> s1Builder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     * @return Whether the s1 field is set.
     */
    @java.lang.Override
    public boolean hasS1() {
      return msgCase_ == 3;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     * @return The s1.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsS1 getS1() {
      if (s1Builder_ == null) {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.SpreadParmsS1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsS1.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return s1Builder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsS1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     */
    public Builder setS1(ca.wise.fuel.proto.SpreadParmsS1 value) {
      if (s1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        s1Builder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     */
    public Builder setS1(
        ca.wise.fuel.proto.SpreadParmsS1.Builder builderForValue) {
      if (s1Builder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        s1Builder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     */
    public Builder mergeS1(ca.wise.fuel.proto.SpreadParmsS1 value) {
      if (s1Builder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsS1.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsS1.newBuilder((ca.wise.fuel.proto.SpreadParmsS1) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          s1Builder_.mergeFrom(value);
        }
        s1Builder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     */
    public Builder clearS1() {
      if (s1Builder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        s1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsS1.Builder getS1Builder() {
      return getS1FieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsS1OrBuilder getS1OrBuilder() {
      if ((msgCase_ == 3) && (s1Builder_ != null)) {
        return s1Builder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (ca.wise.fuel.proto.SpreadParmsS1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsS1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsS1 s1 = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsS1, ca.wise.fuel.proto.SpreadParmsS1.Builder, ca.wise.fuel.proto.SpreadParmsS1OrBuilder> 
        getS1FieldBuilder() {
      if (s1Builder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsS1.getDefaultInstance();
        }
        s1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsS1, ca.wise.fuel.proto.SpreadParmsS1.Builder, ca.wise.fuel.proto.SpreadParmsS1OrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsS1) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return s1Builder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsC1, ca.wise.fuel.proto.SpreadParmsC1.Builder, ca.wise.fuel.proto.SpreadParmsC1OrBuilder> c1Builder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     * @return Whether the c1 field is set.
     */
    @java.lang.Override
    public boolean hasC1() {
      return msgCase_ == 4;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     * @return The c1.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsC1 getC1() {
      if (c1Builder_ == null) {
        if (msgCase_ == 4) {
          return (ca.wise.fuel.proto.SpreadParmsC1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsC1.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return c1Builder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsC1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     */
    public Builder setC1(ca.wise.fuel.proto.SpreadParmsC1 value) {
      if (c1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        c1Builder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     */
    public Builder setC1(
        ca.wise.fuel.proto.SpreadParmsC1.Builder builderForValue) {
      if (c1Builder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        c1Builder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     */
    public Builder mergeC1(ca.wise.fuel.proto.SpreadParmsC1 value) {
      if (c1Builder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsC1.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsC1.newBuilder((ca.wise.fuel.proto.SpreadParmsC1) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          c1Builder_.mergeFrom(value);
        }
        c1Builder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     */
    public Builder clearC1() {
      if (c1Builder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        c1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsC1.Builder getC1Builder() {
      return getC1FieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsC1OrBuilder getC1OrBuilder() {
      if ((msgCase_ == 4) && (c1Builder_ != null)) {
        return c1Builder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (ca.wise.fuel.proto.SpreadParmsC1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsC1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC1 c1 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsC1, ca.wise.fuel.proto.SpreadParmsC1.Builder, ca.wise.fuel.proto.SpreadParmsC1OrBuilder> 
        getC1FieldBuilder() {
      if (c1Builder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsC1.getDefaultInstance();
        }
        c1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsC1, ca.wise.fuel.proto.SpreadParmsC1.Builder, ca.wise.fuel.proto.SpreadParmsC1OrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsC1) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();;
      return c1Builder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsC6, ca.wise.fuel.proto.SpreadParmsC6.Builder, ca.wise.fuel.proto.SpreadParmsC6OrBuilder> c6Builder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     * @return Whether the c6 field is set.
     */
    @java.lang.Override
    public boolean hasC6() {
      return msgCase_ == 5;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     * @return The c6.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsC6 getC6() {
      if (c6Builder_ == null) {
        if (msgCase_ == 5) {
          return (ca.wise.fuel.proto.SpreadParmsC6) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsC6.getDefaultInstance();
      } else {
        if (msgCase_ == 5) {
          return c6Builder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsC6.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     */
    public Builder setC6(ca.wise.fuel.proto.SpreadParmsC6 value) {
      if (c6Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        c6Builder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     */
    public Builder setC6(
        ca.wise.fuel.proto.SpreadParmsC6.Builder builderForValue) {
      if (c6Builder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        c6Builder_.setMessage(builderForValue.build());
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     */
    public Builder mergeC6(ca.wise.fuel.proto.SpreadParmsC6 value) {
      if (c6Builder_ == null) {
        if (msgCase_ == 5 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsC6.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsC6.newBuilder((ca.wise.fuel.proto.SpreadParmsC6) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 5) {
          c6Builder_.mergeFrom(value);
        }
        c6Builder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     */
    public Builder clearC6() {
      if (c6Builder_ == null) {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
        }
        c6Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsC6.Builder getC6Builder() {
      return getC6FieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsC6OrBuilder getC6OrBuilder() {
      if ((msgCase_ == 5) && (c6Builder_ != null)) {
        return c6Builder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 5) {
          return (ca.wise.fuel.proto.SpreadParmsC6) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsC6.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsC6 c6 = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsC6, ca.wise.fuel.proto.SpreadParmsC6.Builder, ca.wise.fuel.proto.SpreadParmsC6OrBuilder> 
        getC6FieldBuilder() {
      if (c6Builder_ == null) {
        if (!(msgCase_ == 5)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsC6.getDefaultInstance();
        }
        c6Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsC6, ca.wise.fuel.proto.SpreadParmsC6.Builder, ca.wise.fuel.proto.SpreadParmsC6OrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsC6) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 5;
      onChanged();;
      return c6Builder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsD1, ca.wise.fuel.proto.SpreadParmsD1.Builder, ca.wise.fuel.proto.SpreadParmsD1OrBuilder> d1Builder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     * @return Whether the d1 field is set.
     */
    @java.lang.Override
    public boolean hasD1() {
      return msgCase_ == 6;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     * @return The d1.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsD1 getD1() {
      if (d1Builder_ == null) {
        if (msgCase_ == 6) {
          return (ca.wise.fuel.proto.SpreadParmsD1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsD1.getDefaultInstance();
      } else {
        if (msgCase_ == 6) {
          return d1Builder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsD1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     */
    public Builder setD1(ca.wise.fuel.proto.SpreadParmsD1 value) {
      if (d1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        d1Builder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     */
    public Builder setD1(
        ca.wise.fuel.proto.SpreadParmsD1.Builder builderForValue) {
      if (d1Builder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        d1Builder_.setMessage(builderForValue.build());
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     */
    public Builder mergeD1(ca.wise.fuel.proto.SpreadParmsD1 value) {
      if (d1Builder_ == null) {
        if (msgCase_ == 6 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsD1.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsD1.newBuilder((ca.wise.fuel.proto.SpreadParmsD1) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 6) {
          d1Builder_.mergeFrom(value);
        }
        d1Builder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     */
    public Builder clearD1() {
      if (d1Builder_ == null) {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
        }
        d1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsD1.Builder getD1Builder() {
      return getD1FieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsD1OrBuilder getD1OrBuilder() {
      if ((msgCase_ == 6) && (d1Builder_ != null)) {
        return d1Builder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 6) {
          return (ca.wise.fuel.proto.SpreadParmsD1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsD1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsD1 d1 = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsD1, ca.wise.fuel.proto.SpreadParmsD1.Builder, ca.wise.fuel.proto.SpreadParmsD1OrBuilder> 
        getD1FieldBuilder() {
      if (d1Builder_ == null) {
        if (!(msgCase_ == 6)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsD1.getDefaultInstance();
        }
        d1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsD1, ca.wise.fuel.proto.SpreadParmsD1.Builder, ca.wise.fuel.proto.SpreadParmsD1OrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsD1) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 6;
      onChanged();;
      return d1Builder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsNz, ca.wise.fuel.proto.SpreadParmsNz.Builder, ca.wise.fuel.proto.SpreadParmsNzOrBuilder> nzBuilder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     * @return Whether the nz field is set.
     */
    @java.lang.Override
    public boolean hasNz() {
      return msgCase_ == 7;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     * @return The nz.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsNz getNz() {
      if (nzBuilder_ == null) {
        if (msgCase_ == 7) {
          return (ca.wise.fuel.proto.SpreadParmsNz) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsNz.getDefaultInstance();
      } else {
        if (msgCase_ == 7) {
          return nzBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsNz.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     */
    public Builder setNz(ca.wise.fuel.proto.SpreadParmsNz value) {
      if (nzBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        nzBuilder_.setMessage(value);
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     */
    public Builder setNz(
        ca.wise.fuel.proto.SpreadParmsNz.Builder builderForValue) {
      if (nzBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        nzBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     */
    public Builder mergeNz(ca.wise.fuel.proto.SpreadParmsNz value) {
      if (nzBuilder_ == null) {
        if (msgCase_ == 7 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsNz.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsNz.newBuilder((ca.wise.fuel.proto.SpreadParmsNz) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 7) {
          nzBuilder_.mergeFrom(value);
        }
        nzBuilder_.setMessage(value);
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     */
    public Builder clearNz() {
      if (nzBuilder_ == null) {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
        }
        nzBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsNz.Builder getNzBuilder() {
      return getNzFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsNzOrBuilder getNzOrBuilder() {
      if ((msgCase_ == 7) && (nzBuilder_ != null)) {
        return nzBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 7) {
          return (ca.wise.fuel.proto.SpreadParmsNz) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsNz.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNz nz = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsNz, ca.wise.fuel.proto.SpreadParmsNz.Builder, ca.wise.fuel.proto.SpreadParmsNzOrBuilder> 
        getNzFieldBuilder() {
      if (nzBuilder_ == null) {
        if (!(msgCase_ == 7)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsNz.getDefaultInstance();
        }
        nzBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsNz, ca.wise.fuel.proto.SpreadParmsNz.Builder, ca.wise.fuel.proto.SpreadParmsNzOrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsNz) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 7;
      onChanged();;
      return nzBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsO1, ca.wise.fuel.proto.SpreadParmsO1.Builder, ca.wise.fuel.proto.SpreadParmsO1OrBuilder> o1Builder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     * @return Whether the o1 field is set.
     */
    @java.lang.Override
    public boolean hasO1() {
      return msgCase_ == 8;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     * @return The o1.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsO1 getO1() {
      if (o1Builder_ == null) {
        if (msgCase_ == 8) {
          return (ca.wise.fuel.proto.SpreadParmsO1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsO1.getDefaultInstance();
      } else {
        if (msgCase_ == 8) {
          return o1Builder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsO1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     */
    public Builder setO1(ca.wise.fuel.proto.SpreadParmsO1 value) {
      if (o1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        o1Builder_.setMessage(value);
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     */
    public Builder setO1(
        ca.wise.fuel.proto.SpreadParmsO1.Builder builderForValue) {
      if (o1Builder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        o1Builder_.setMessage(builderForValue.build());
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     */
    public Builder mergeO1(ca.wise.fuel.proto.SpreadParmsO1 value) {
      if (o1Builder_ == null) {
        if (msgCase_ == 8 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsO1.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsO1.newBuilder((ca.wise.fuel.proto.SpreadParmsO1) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 8) {
          o1Builder_.mergeFrom(value);
        }
        o1Builder_.setMessage(value);
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     */
    public Builder clearO1() {
      if (o1Builder_ == null) {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
        }
        o1Builder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsO1.Builder getO1Builder() {
      return getO1FieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsO1OrBuilder getO1OrBuilder() {
      if ((msgCase_ == 8) && (o1Builder_ != null)) {
        return o1Builder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 8) {
          return (ca.wise.fuel.proto.SpreadParmsO1) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsO1.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1 o1 = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsO1, ca.wise.fuel.proto.SpreadParmsO1.Builder, ca.wise.fuel.proto.SpreadParmsO1OrBuilder> 
        getO1FieldBuilder() {
      if (o1Builder_ == null) {
        if (!(msgCase_ == 8)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsO1.getDefaultInstance();
        }
        o1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsO1, ca.wise.fuel.proto.SpreadParmsO1.Builder, ca.wise.fuel.proto.SpreadParmsO1OrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsO1) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 8;
      onChanged();;
      return o1Builder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsO1ab, ca.wise.fuel.proto.SpreadParmsO1ab.Builder, ca.wise.fuel.proto.SpreadParmsO1abOrBuilder> o1AbBuilder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     * @return Whether the o1ab field is set.
     */
    @java.lang.Override
    public boolean hasO1Ab() {
      return msgCase_ == 9;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     * @return The o1ab.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsO1ab getO1Ab() {
      if (o1AbBuilder_ == null) {
        if (msgCase_ == 9) {
          return (ca.wise.fuel.proto.SpreadParmsO1ab) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsO1ab.getDefaultInstance();
      } else {
        if (msgCase_ == 9) {
          return o1AbBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsO1ab.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     */
    public Builder setO1Ab(ca.wise.fuel.proto.SpreadParmsO1ab value) {
      if (o1AbBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        o1AbBuilder_.setMessage(value);
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     */
    public Builder setO1Ab(
        ca.wise.fuel.proto.SpreadParmsO1ab.Builder builderForValue) {
      if (o1AbBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        o1AbBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     */
    public Builder mergeO1Ab(ca.wise.fuel.proto.SpreadParmsO1ab value) {
      if (o1AbBuilder_ == null) {
        if (msgCase_ == 9 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsO1ab.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsO1ab.newBuilder((ca.wise.fuel.proto.SpreadParmsO1ab) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 9) {
          o1AbBuilder_.mergeFrom(value);
        }
        o1AbBuilder_.setMessage(value);
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     */
    public Builder clearO1Ab() {
      if (o1AbBuilder_ == null) {
        if (msgCase_ == 9) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 9) {
          msgCase_ = 0;
          msg_ = null;
        }
        o1AbBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsO1ab.Builder getO1AbBuilder() {
      return getO1AbFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsO1abOrBuilder getO1AbOrBuilder() {
      if ((msgCase_ == 9) && (o1AbBuilder_ != null)) {
        return o1AbBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 9) {
          return (ca.wise.fuel.proto.SpreadParmsO1ab) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsO1ab.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsO1ab o1ab = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsO1ab, ca.wise.fuel.proto.SpreadParmsO1ab.Builder, ca.wise.fuel.proto.SpreadParmsO1abOrBuilder> 
        getO1AbFieldBuilder() {
      if (o1AbBuilder_ == null) {
        if (!(msgCase_ == 9)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsO1ab.getDefaultInstance();
        }
        o1AbBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsO1ab, ca.wise.fuel.proto.SpreadParmsO1ab.Builder, ca.wise.fuel.proto.SpreadParmsO1abOrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsO1ab) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 9;
      onChanged();;
      return o1AbBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsMixed, ca.wise.fuel.proto.SpreadParmsMixed.Builder, ca.wise.fuel.proto.SpreadParmsMixedOrBuilder> mixedBuilder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     * @return Whether the mixed field is set.
     */
    @java.lang.Override
    public boolean hasMixed() {
      return msgCase_ == 10;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     * @return The mixed.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsMixed getMixed() {
      if (mixedBuilder_ == null) {
        if (msgCase_ == 10) {
          return (ca.wise.fuel.proto.SpreadParmsMixed) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsMixed.getDefaultInstance();
      } else {
        if (msgCase_ == 10) {
          return mixedBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsMixed.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     */
    public Builder setMixed(ca.wise.fuel.proto.SpreadParmsMixed value) {
      if (mixedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        mixedBuilder_.setMessage(value);
      }
      msgCase_ = 10;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     */
    public Builder setMixed(
        ca.wise.fuel.proto.SpreadParmsMixed.Builder builderForValue) {
      if (mixedBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        mixedBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 10;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     */
    public Builder mergeMixed(ca.wise.fuel.proto.SpreadParmsMixed value) {
      if (mixedBuilder_ == null) {
        if (msgCase_ == 10 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsMixed.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsMixed.newBuilder((ca.wise.fuel.proto.SpreadParmsMixed) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 10) {
          mixedBuilder_.mergeFrom(value);
        }
        mixedBuilder_.setMessage(value);
      }
      msgCase_ = 10;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     */
    public Builder clearMixed() {
      if (mixedBuilder_ == null) {
        if (msgCase_ == 10) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 10) {
          msgCase_ = 0;
          msg_ = null;
        }
        mixedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsMixed.Builder getMixedBuilder() {
      return getMixedFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsMixedOrBuilder getMixedOrBuilder() {
      if ((msgCase_ == 10) && (mixedBuilder_ != null)) {
        return mixedBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 10) {
          return (ca.wise.fuel.proto.SpreadParmsMixed) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsMixed.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixed mixed = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsMixed, ca.wise.fuel.proto.SpreadParmsMixed.Builder, ca.wise.fuel.proto.SpreadParmsMixedOrBuilder> 
        getMixedFieldBuilder() {
      if (mixedBuilder_ == null) {
        if (!(msgCase_ == 10)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsMixed.getDefaultInstance();
        }
        mixedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsMixed, ca.wise.fuel.proto.SpreadParmsMixed.Builder, ca.wise.fuel.proto.SpreadParmsMixedOrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsMixed) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 10;
      onChanged();;
      return mixedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsMixedDead, ca.wise.fuel.proto.SpreadParmsMixedDead.Builder, ca.wise.fuel.proto.SpreadParmsMixedDeadOrBuilder> mixedDeadBuilder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     * @return Whether the mixedDead field is set.
     */
    @java.lang.Override
    public boolean hasMixedDead() {
      return msgCase_ == 11;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     * @return The mixedDead.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsMixedDead getMixedDead() {
      if (mixedDeadBuilder_ == null) {
        if (msgCase_ == 11) {
          return (ca.wise.fuel.proto.SpreadParmsMixedDead) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsMixedDead.getDefaultInstance();
      } else {
        if (msgCase_ == 11) {
          return mixedDeadBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsMixedDead.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     */
    public Builder setMixedDead(ca.wise.fuel.proto.SpreadParmsMixedDead value) {
      if (mixedDeadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        mixedDeadBuilder_.setMessage(value);
      }
      msgCase_ = 11;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     */
    public Builder setMixedDead(
        ca.wise.fuel.proto.SpreadParmsMixedDead.Builder builderForValue) {
      if (mixedDeadBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        mixedDeadBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 11;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     */
    public Builder mergeMixedDead(ca.wise.fuel.proto.SpreadParmsMixedDead value) {
      if (mixedDeadBuilder_ == null) {
        if (msgCase_ == 11 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsMixedDead.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsMixedDead.newBuilder((ca.wise.fuel.proto.SpreadParmsMixedDead) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 11) {
          mixedDeadBuilder_.mergeFrom(value);
        }
        mixedDeadBuilder_.setMessage(value);
      }
      msgCase_ = 11;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     */
    public Builder clearMixedDead() {
      if (mixedDeadBuilder_ == null) {
        if (msgCase_ == 11) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 11) {
          msgCase_ = 0;
          msg_ = null;
        }
        mixedDeadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsMixedDead.Builder getMixedDeadBuilder() {
      return getMixedDeadFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsMixedDeadOrBuilder getMixedDeadOrBuilder() {
      if ((msgCase_ == 11) && (mixedDeadBuilder_ != null)) {
        return mixedDeadBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 11) {
          return (ca.wise.fuel.proto.SpreadParmsMixedDead) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsMixedDead.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsMixedDead mixedDead = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsMixedDead, ca.wise.fuel.proto.SpreadParmsMixedDead.Builder, ca.wise.fuel.proto.SpreadParmsMixedDeadOrBuilder> 
        getMixedDeadFieldBuilder() {
      if (mixedDeadBuilder_ == null) {
        if (!(msgCase_ == 11)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsMixedDead.getDefaultInstance();
        }
        mixedDeadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsMixedDead, ca.wise.fuel.proto.SpreadParmsMixedDead.Builder, ca.wise.fuel.proto.SpreadParmsMixedDeadOrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsMixedDead) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 11;
      onChanged();;
      return mixedDeadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsNon, ca.wise.fuel.proto.SpreadParmsNon.Builder, ca.wise.fuel.proto.SpreadParmsNonOrBuilder> nonBuilder_;
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     * @return Whether the non field is set.
     */
    @java.lang.Override
    public boolean hasNon() {
      return msgCase_ == 12;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     * @return The non.
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsNon getNon() {
      if (nonBuilder_ == null) {
        if (msgCase_ == 12) {
          return (ca.wise.fuel.proto.SpreadParmsNon) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsNon.getDefaultInstance();
      } else {
        if (msgCase_ == 12) {
          return nonBuilder_.getMessage();
        }
        return ca.wise.fuel.proto.SpreadParmsNon.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     */
    public Builder setNon(ca.wise.fuel.proto.SpreadParmsNon value) {
      if (nonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        nonBuilder_.setMessage(value);
      }
      msgCase_ = 12;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     */
    public Builder setNon(
        ca.wise.fuel.proto.SpreadParmsNon.Builder builderForValue) {
      if (nonBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        nonBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 12;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     */
    public Builder mergeNon(ca.wise.fuel.proto.SpreadParmsNon value) {
      if (nonBuilder_ == null) {
        if (msgCase_ == 12 &&
            msg_ != ca.wise.fuel.proto.SpreadParmsNon.getDefaultInstance()) {
          msg_ = ca.wise.fuel.proto.SpreadParmsNon.newBuilder((ca.wise.fuel.proto.SpreadParmsNon) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 12) {
          nonBuilder_.mergeFrom(value);
        }
        nonBuilder_.setMessage(value);
      }
      msgCase_ = 12;
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     */
    public Builder clearNon() {
      if (nonBuilder_ == null) {
        if (msgCase_ == 12) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 12) {
          msgCase_ = 0;
          msg_ = null;
        }
        nonBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     */
    public ca.wise.fuel.proto.SpreadParmsNon.Builder getNonBuilder() {
      return getNonFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     */
    @java.lang.Override
    public ca.wise.fuel.proto.SpreadParmsNonOrBuilder getNonOrBuilder() {
      if ((msgCase_ == 12) && (nonBuilder_ != null)) {
        return nonBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 12) {
          return (ca.wise.fuel.proto.SpreadParmsNon) msg_;
        }
        return ca.wise.fuel.proto.SpreadParmsNon.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.FuelProto.SpreadParmsNon non = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.fuel.proto.SpreadParmsNon, ca.wise.fuel.proto.SpreadParmsNon.Builder, ca.wise.fuel.proto.SpreadParmsNonOrBuilder> 
        getNonFieldBuilder() {
      if (nonBuilder_ == null) {
        if (!(msgCase_ == 12)) {
          msg_ = ca.wise.fuel.proto.SpreadParmsNon.getDefaultInstance();
        }
        nonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.fuel.proto.SpreadParmsNon, ca.wise.fuel.proto.SpreadParmsNon.Builder, ca.wise.fuel.proto.SpreadParmsNonOrBuilder>(
                (ca.wise.fuel.proto.SpreadParmsNon) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 12;
      onChanged();;
      return nonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.FuelProto.SpreadParmsAttribute)
  }

  // @@protoc_insertion_point(class_scope:WISE.FuelProto.SpreadParmsAttribute)
  private static final ca.wise.fuel.proto.SpreadParmsAttribute DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.fuel.proto.SpreadParmsAttribute();
  }

  public static ca.wise.fuel.proto.SpreadParmsAttribute getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpreadParmsAttribute>
      PARSER = new com.google.protobuf.AbstractParser<SpreadParmsAttribute>() {
    @java.lang.Override
    public SpreadParmsAttribute parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpreadParmsAttribute(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpreadParmsAttribute> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpreadParmsAttribute> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.fuel.proto.SpreadParmsAttribute getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

